-- Migration: Add mipaquete_code to cities and populate with DANE codes
-- Run this in Supabase SQL Editor

ALTER TABLE cities ADD COLUMN IF NOT EXISTS mipaquete_code VARCHAR(20);

UPDATE cities SET mipaquete_code = '05001000' WHERE LOWER(name) = LOWER('Medellín');
UPDATE cities SET mipaquete_code = '05002000' WHERE LOWER(name) = LOWER('Abejorral');
UPDATE cities SET mipaquete_code = '05004000' WHERE LOWER(name) = LOWER('Abriaquí');
UPDATE cities SET mipaquete_code = '05021000' WHERE LOWER(name) = LOWER('Alejandría');
UPDATE cities SET mipaquete_code = '05030000' WHERE LOWER(name) = LOWER('Amagá');
UPDATE cities SET mipaquete_code = '05031000' WHERE LOWER(name) = LOWER('Amalfi');
UPDATE cities SET mipaquete_code = '05034000' WHERE LOWER(name) = LOWER('Andes');
UPDATE cities SET mipaquete_code = '05036000' WHERE LOWER(name) = LOWER('Angelópolis');
UPDATE cities SET mipaquete_code = '05038000' WHERE LOWER(name) = LOWER('Angostura');
UPDATE cities SET mipaquete_code = '05040000' WHERE LOWER(name) = LOWER('Anorí');
UPDATE cities SET mipaquete_code = '05042000' WHERE LOWER(name) = LOWER('Santa Fé De Antioquia');
UPDATE cities SET mipaquete_code = '05044000' WHERE LOWER(name) = LOWER('Anzá');
UPDATE cities SET mipaquete_code = '05045000' WHERE LOWER(name) = LOWER('Apartadó');
UPDATE cities SET mipaquete_code = '05051000' WHERE LOWER(name) = LOWER('Arboletes');
UPDATE cities SET mipaquete_code = '05055000' WHERE LOWER(name) = LOWER('Argelia');
UPDATE cities SET mipaquete_code = '05059000' WHERE LOWER(name) = LOWER('Armenia');
UPDATE cities SET mipaquete_code = '05079000' WHERE LOWER(name) = LOWER('Barbosa');
UPDATE cities SET mipaquete_code = '05086000' WHERE LOWER(name) = LOWER('Belmira');
UPDATE cities SET mipaquete_code = '05088000' WHERE LOWER(name) = LOWER('Bello');
UPDATE cities SET mipaquete_code = '05091000' WHERE LOWER(name) = LOWER('Betania');
UPDATE cities SET mipaquete_code = '05093000' WHERE LOWER(name) = LOWER('Betulia');
UPDATE cities SET mipaquete_code = '05101000' WHERE LOWER(name) = LOWER('Ciudad Bolívar');
UPDATE cities SET mipaquete_code = '05107000' WHERE LOWER(name) = LOWER('Briceño');
UPDATE cities SET mipaquete_code = '05113000' WHERE LOWER(name) = LOWER('Buriticá');
UPDATE cities SET mipaquete_code = '05120000' WHERE LOWER(name) = LOWER('Cáceres');
UPDATE cities SET mipaquete_code = '05125000' WHERE LOWER(name) = LOWER('Caicedo');
UPDATE cities SET mipaquete_code = '05129000' WHERE LOWER(name) = LOWER('Caldas');
UPDATE cities SET mipaquete_code = '05134000' WHERE LOWER(name) = LOWER('Campamento');
UPDATE cities SET mipaquete_code = '05138000' WHERE LOWER(name) = LOWER('Cañasgordas');
UPDATE cities SET mipaquete_code = '05142000' WHERE LOWER(name) = LOWER('Caracolí');
UPDATE cities SET mipaquete_code = '05145000' WHERE LOWER(name) = LOWER('Caramanta');
UPDATE cities SET mipaquete_code = '05147000' WHERE LOWER(name) = LOWER('Carepa');
UPDATE cities SET mipaquete_code = '05148000' WHERE LOWER(name) = LOWER('El Carmen De Viboral');
UPDATE cities SET mipaquete_code = '05150000' WHERE LOWER(name) = LOWER('Carolina');
UPDATE cities SET mipaquete_code = '05154000' WHERE LOWER(name) = LOWER('Caucasia');
UPDATE cities SET mipaquete_code = '05172000' WHERE LOWER(name) = LOWER('Chigorodó');
UPDATE cities SET mipaquete_code = '05190000' WHERE LOWER(name) = LOWER('Cisneros');
UPDATE cities SET mipaquete_code = '05197000' WHERE LOWER(name) = LOWER('Cocorná');
UPDATE cities SET mipaquete_code = '05206000' WHERE LOWER(name) = LOWER('Concepción');
UPDATE cities SET mipaquete_code = '05209000' WHERE LOWER(name) = LOWER('Concordia');
UPDATE cities SET mipaquete_code = '05212000' WHERE LOWER(name) = LOWER('Copacabana');
UPDATE cities SET mipaquete_code = '05234000' WHERE LOWER(name) = LOWER('Dabeiba');
UPDATE cities SET mipaquete_code = '05237000' WHERE LOWER(name) = LOWER('Donmatías');
UPDATE cities SET mipaquete_code = '05240000' WHERE LOWER(name) = LOWER('Ebéjico');
UPDATE cities SET mipaquete_code = '05250000' WHERE LOWER(name) = LOWER('El Bagre');
UPDATE cities SET mipaquete_code = '05264000' WHERE LOWER(name) = LOWER('Entrerríos');
UPDATE cities SET mipaquete_code = '05266000' WHERE LOWER(name) = LOWER('Envigado');
UPDATE cities SET mipaquete_code = '05282000' WHERE LOWER(name) = LOWER('Fredonia');
UPDATE cities SET mipaquete_code = '05284000' WHERE LOWER(name) = LOWER('Frontino');
UPDATE cities SET mipaquete_code = '05306000' WHERE LOWER(name) = LOWER('Giraldo');
UPDATE cities SET mipaquete_code = '05308000' WHERE LOWER(name) = LOWER('Girardota');
UPDATE cities SET mipaquete_code = '05310000' WHERE LOWER(name) = LOWER('Gómez Plata');
UPDATE cities SET mipaquete_code = '05313000' WHERE LOWER(name) = LOWER('Granada');
UPDATE cities SET mipaquete_code = '05315000' WHERE LOWER(name) = LOWER('Guadalupe');
UPDATE cities SET mipaquete_code = '05318000' WHERE LOWER(name) = LOWER('Guarne');
UPDATE cities SET mipaquete_code = '05321000' WHERE LOWER(name) = LOWER('Guatapé');
UPDATE cities SET mipaquete_code = '05347000' WHERE LOWER(name) = LOWER('Heliconia');
UPDATE cities SET mipaquete_code = '05353000' WHERE LOWER(name) = LOWER('Hispania');
UPDATE cities SET mipaquete_code = '05360000' WHERE LOWER(name) = LOWER('Itagüí');
UPDATE cities SET mipaquete_code = '05361000' WHERE LOWER(name) = LOWER('Ituango');
UPDATE cities SET mipaquete_code = '05364000' WHERE LOWER(name) = LOWER('Jardín');
UPDATE cities SET mipaquete_code = '05368000' WHERE LOWER(name) = LOWER('Jericó');
UPDATE cities SET mipaquete_code = '05376000' WHERE LOWER(name) = LOWER('La Ceja');
UPDATE cities SET mipaquete_code = '05380000' WHERE LOWER(name) = LOWER('La Estrella');
UPDATE cities SET mipaquete_code = '05390000' WHERE LOWER(name) = LOWER('La Pintada');
UPDATE cities SET mipaquete_code = '05400000' WHERE LOWER(name) = LOWER('La Unión');
UPDATE cities SET mipaquete_code = '05411000' WHERE LOWER(name) = LOWER('Liborina');
UPDATE cities SET mipaquete_code = '05425000' WHERE LOWER(name) = LOWER('Maceo');
UPDATE cities SET mipaquete_code = '05440000' WHERE LOWER(name) = LOWER('Marinilla');
UPDATE cities SET mipaquete_code = '05467000' WHERE LOWER(name) = LOWER('Montebello');
UPDATE cities SET mipaquete_code = '05475000' WHERE LOWER(name) = LOWER('Murindó');
UPDATE cities SET mipaquete_code = '05480000' WHERE LOWER(name) = LOWER('Mutatá');
UPDATE cities SET mipaquete_code = '05483000' WHERE LOWER(name) = LOWER('Nariño');
UPDATE cities SET mipaquete_code = '05490000' WHERE LOWER(name) = LOWER('Necoclí');
UPDATE cities SET mipaquete_code = '05495000' WHERE LOWER(name) = LOWER('Nechí');
UPDATE cities SET mipaquete_code = '05501000' WHERE LOWER(name) = LOWER('Olaya');
UPDATE cities SET mipaquete_code = '05541000' WHERE LOWER(name) = LOWER('Peñol');
UPDATE cities SET mipaquete_code = '05543000' WHERE LOWER(name) = LOWER('Peque');
UPDATE cities SET mipaquete_code = '05576000' WHERE LOWER(name) = LOWER('Pueblorrico');
UPDATE cities SET mipaquete_code = '05579000' WHERE LOWER(name) = LOWER('Puerto Berrío');
UPDATE cities SET mipaquete_code = '05585000' WHERE LOWER(name) = LOWER('Puerto Nare');
UPDATE cities SET mipaquete_code = '05591000' WHERE LOWER(name) = LOWER('Puerto Triunfo');
UPDATE cities SET mipaquete_code = '05604000' WHERE LOWER(name) = LOWER('Remedios');
UPDATE cities SET mipaquete_code = '05607000' WHERE LOWER(name) = LOWER('Retiro');
UPDATE cities SET mipaquete_code = '05615000' WHERE LOWER(name) = LOWER('Rionegro');
UPDATE cities SET mipaquete_code = '05628000' WHERE LOWER(name) = LOWER('Sabanalarga');
UPDATE cities SET mipaquete_code = '05631000' WHERE LOWER(name) = LOWER('Sabaneta');
UPDATE cities SET mipaquete_code = '05642000' WHERE LOWER(name) = LOWER('Salgar');
UPDATE cities SET mipaquete_code = '05647000' WHERE LOWER(name) = LOWER('San Andrés De Cuerquía');
UPDATE cities SET mipaquete_code = '05649000' WHERE LOWER(name) = LOWER('San Carlos');
UPDATE cities SET mipaquete_code = '05652000' WHERE LOWER(name) = LOWER('San Francisco');
UPDATE cities SET mipaquete_code = '05656000' WHERE LOWER(name) = LOWER('San Jerónimo');
UPDATE cities SET mipaquete_code = '05658000' WHERE LOWER(name) = LOWER('San José De La Montaña');
UPDATE cities SET mipaquete_code = '05659000' WHERE LOWER(name) = LOWER('San Juan De Urabá');
UPDATE cities SET mipaquete_code = '05660000' WHERE LOWER(name) = LOWER('San Luis');
UPDATE cities SET mipaquete_code = '05664000' WHERE LOWER(name) = LOWER('San Pedro De Los Milagros');
UPDATE cities SET mipaquete_code = '05665000' WHERE LOWER(name) = LOWER('San Pedro De Urabá');
UPDATE cities SET mipaquete_code = '05667000' WHERE LOWER(name) = LOWER('San Rafael');
UPDATE cities SET mipaquete_code = '05670000' WHERE LOWER(name) = LOWER('San Roque');
UPDATE cities SET mipaquete_code = '05674000' WHERE LOWER(name) = LOWER('San Vicente Ferrer');
UPDATE cities SET mipaquete_code = '05679000' WHERE LOWER(name) = LOWER('Santa Bárbara');
UPDATE cities SET mipaquete_code = '05686000' WHERE LOWER(name) = LOWER('Santa Rosa De Osos');
UPDATE cities SET mipaquete_code = '05690000' WHERE LOWER(name) = LOWER('Santo Domingo');
UPDATE cities SET mipaquete_code = '05697000' WHERE LOWER(name) = LOWER('El Santuario');
UPDATE cities SET mipaquete_code = '05736000' WHERE LOWER(name) = LOWER('Segovia');
UPDATE cities SET mipaquete_code = '05756000' WHERE LOWER(name) = LOWER('Sonsón');
UPDATE cities SET mipaquete_code = '05761000' WHERE LOWER(name) = LOWER('Sopetrán');
UPDATE cities SET mipaquete_code = '05789000' WHERE LOWER(name) = LOWER('Támesis');
UPDATE cities SET mipaquete_code = '05790000' WHERE LOWER(name) = LOWER('Tarazá');
UPDATE cities SET mipaquete_code = '05792000' WHERE LOWER(name) = LOWER('Tarso');
UPDATE cities SET mipaquete_code = '05809000' WHERE LOWER(name) = LOWER('Titiribí');
UPDATE cities SET mipaquete_code = '05819000' WHERE LOWER(name) = LOWER('Toledo');
UPDATE cities SET mipaquete_code = '05837000' WHERE LOWER(name) = LOWER('Turbo');
UPDATE cities SET mipaquete_code = '05842000' WHERE LOWER(name) = LOWER('Uramita');
UPDATE cities SET mipaquete_code = '05847000' WHERE LOWER(name) = LOWER('Urrao');
UPDATE cities SET mipaquete_code = '05854000' WHERE LOWER(name) = LOWER('Valdivia');
UPDATE cities SET mipaquete_code = '05856000' WHERE LOWER(name) = LOWER('Valparaíso');
UPDATE cities SET mipaquete_code = '05858000' WHERE LOWER(name) = LOWER('Vegachí');
UPDATE cities SET mipaquete_code = '05861000' WHERE LOWER(name) = LOWER('Venecia');
UPDATE cities SET mipaquete_code = '05873000' WHERE LOWER(name) = LOWER('Vigía Del Fuerte');
UPDATE cities SET mipaquete_code = '05885000' WHERE LOWER(name) = LOWER('Yalí');
UPDATE cities SET mipaquete_code = '05887000' WHERE LOWER(name) = LOWER('Yarumal');
UPDATE cities SET mipaquete_code = '05890000' WHERE LOWER(name) = LOWER('Yolombó');
UPDATE cities SET mipaquete_code = '05893000' WHERE LOWER(name) = LOWER('Yondó');
UPDATE cities SET mipaquete_code = '05895000' WHERE LOWER(name) = LOWER('Zaragoza');
UPDATE cities SET mipaquete_code = '08001000' WHERE LOWER(name) = LOWER('Barranquilla');
UPDATE cities SET mipaquete_code = '08078000' WHERE LOWER(name) = LOWER('Baranoa');
UPDATE cities SET mipaquete_code = '08137000' WHERE LOWER(name) = LOWER('Campo De La Cruz');
UPDATE cities SET mipaquete_code = '08141000' WHERE LOWER(name) = LOWER('Candelaria');
UPDATE cities SET mipaquete_code = '08296000' WHERE LOWER(name) = LOWER('Galapa');
UPDATE cities SET mipaquete_code = '08372000' WHERE LOWER(name) = LOWER('Juan De Acosta');
UPDATE cities SET mipaquete_code = '08421000' WHERE LOWER(name) = LOWER('Luruaco');
UPDATE cities SET mipaquete_code = '08433000' WHERE LOWER(name) = LOWER('Malambo');
UPDATE cities SET mipaquete_code = '08436000' WHERE LOWER(name) = LOWER('Manatí');
UPDATE cities SET mipaquete_code = '08520000' WHERE LOWER(name) = LOWER('Palmar De Varela');
UPDATE cities SET mipaquete_code = '08549000' WHERE LOWER(name) = LOWER('Piojó');
UPDATE cities SET mipaquete_code = '08558000' WHERE LOWER(name) = LOWER('Polonuevo');
UPDATE cities SET mipaquete_code = '08560000' WHERE LOWER(name) = LOWER('Ponedera');
UPDATE cities SET mipaquete_code = '08573000' WHERE LOWER(name) = LOWER('Puerto Colombia');
UPDATE cities SET mipaquete_code = '08606000' WHERE LOWER(name) = LOWER('Repelón');
UPDATE cities SET mipaquete_code = '08634000' WHERE LOWER(name) = LOWER('Sabanagrande');
UPDATE cities SET mipaquete_code = '08638000' WHERE LOWER(name) = LOWER('Sabanalarga');
UPDATE cities SET mipaquete_code = '08675000' WHERE LOWER(name) = LOWER('Santa Lucía');
UPDATE cities SET mipaquete_code = '08685000' WHERE LOWER(name) = LOWER('Santo Tomás');
UPDATE cities SET mipaquete_code = '08758000' WHERE LOWER(name) = LOWER('Soledad');
UPDATE cities SET mipaquete_code = '08770000' WHERE LOWER(name) = LOWER('Suan');
UPDATE cities SET mipaquete_code = '08832000' WHERE LOWER(name) = LOWER('Tubará');
UPDATE cities SET mipaquete_code = '08849000' WHERE LOWER(name) = LOWER('Usiacurí');
UPDATE cities SET mipaquete_code = '11001000' WHERE LOWER(name) = LOWER('Bogotá, D.C.');
UPDATE cities SET mipaquete_code = '13001000' WHERE LOWER(name) = LOWER('Cartagena De Indias');
UPDATE cities SET mipaquete_code = '13006000' WHERE LOWER(name) = LOWER('Achí');
UPDATE cities SET mipaquete_code = '13030000' WHERE LOWER(name) = LOWER('Altos Del Rosario');
UPDATE cities SET mipaquete_code = '13042000' WHERE LOWER(name) = LOWER('Arenal');
UPDATE cities SET mipaquete_code = '13052000' WHERE LOWER(name) = LOWER('Arjona');
UPDATE cities SET mipaquete_code = '13062000' WHERE LOWER(name) = LOWER('Arroyohondo');
UPDATE cities SET mipaquete_code = '13074000' WHERE LOWER(name) = LOWER('Barranco De Loba');
UPDATE cities SET mipaquete_code = '13140000' WHERE LOWER(name) = LOWER('Calamar');
UPDATE cities SET mipaquete_code = '13160000' WHERE LOWER(name) = LOWER('Cantagallo');
UPDATE cities SET mipaquete_code = '13188000' WHERE LOWER(name) = LOWER('Cicuco');
UPDATE cities SET mipaquete_code = '13212000' WHERE LOWER(name) = LOWER('Córdoba');
UPDATE cities SET mipaquete_code = '13222000' WHERE LOWER(name) = LOWER('Clemencia');
UPDATE cities SET mipaquete_code = '13244000' WHERE LOWER(name) = LOWER('El Carmen De Bolívar');
UPDATE cities SET mipaquete_code = '13248000' WHERE LOWER(name) = LOWER('El Guamo');
UPDATE cities SET mipaquete_code = '13268000' WHERE LOWER(name) = LOWER('El Peñón');
UPDATE cities SET mipaquete_code = '13300000' WHERE LOWER(name) = LOWER('Hatillo De Loba');
UPDATE cities SET mipaquete_code = '13430000' WHERE LOWER(name) = LOWER('Magangué');
UPDATE cities SET mipaquete_code = '13433000' WHERE LOWER(name) = LOWER('Mahates');
UPDATE cities SET mipaquete_code = '13440000' WHERE LOWER(name) = LOWER('Margarita');
UPDATE cities SET mipaquete_code = '13442000' WHERE LOWER(name) = LOWER('María La Baja');
UPDATE cities SET mipaquete_code = '13458000' WHERE LOWER(name) = LOWER('Montecristo');
UPDATE cities SET mipaquete_code = '13468000' WHERE LOWER(name) = LOWER('Santa Cruz De Mompox');
UPDATE cities SET mipaquete_code = '13473000' WHERE LOWER(name) = LOWER('Morales');
UPDATE cities SET mipaquete_code = '13490000' WHERE LOWER(name) = LOWER('Norosí');
UPDATE cities SET mipaquete_code = '13549000' WHERE LOWER(name) = LOWER('Pinillos');
UPDATE cities SET mipaquete_code = '13580000' WHERE LOWER(name) = LOWER('Regidor');
UPDATE cities SET mipaquete_code = '13600000' WHERE LOWER(name) = LOWER('Río Viejo');
UPDATE cities SET mipaquete_code = '13620000' WHERE LOWER(name) = LOWER('San Cristóbal');
UPDATE cities SET mipaquete_code = '13647000' WHERE LOWER(name) = LOWER('San Estanislao');
UPDATE cities SET mipaquete_code = '13650000' WHERE LOWER(name) = LOWER('San Fernando');
UPDATE cities SET mipaquete_code = '13654000' WHERE LOWER(name) = LOWER('San Jacinto');
UPDATE cities SET mipaquete_code = '13655000' WHERE LOWER(name) = LOWER('San Jacinto Del Cauca');
UPDATE cities SET mipaquete_code = '13657000' WHERE LOWER(name) = LOWER('San Juan Nepomuceno');
UPDATE cities SET mipaquete_code = '13667000' WHERE LOWER(name) = LOWER('San Martín De Loba');
UPDATE cities SET mipaquete_code = '13670000' WHERE LOWER(name) = LOWER('San Pablo');
UPDATE cities SET mipaquete_code = '13673000' WHERE LOWER(name) = LOWER('Santa Catalina');
UPDATE cities SET mipaquete_code = '13683000' WHERE LOWER(name) = LOWER('Santa Rosa');
UPDATE cities SET mipaquete_code = '13688000' WHERE LOWER(name) = LOWER('Santa Rosa Del Sur');
UPDATE cities SET mipaquete_code = '13744000' WHERE LOWER(name) = LOWER('Simití');
UPDATE cities SET mipaquete_code = '13760000' WHERE LOWER(name) = LOWER('Soplaviento');
UPDATE cities SET mipaquete_code = '13780000' WHERE LOWER(name) = LOWER('Talaigua Nuevo');
UPDATE cities SET mipaquete_code = '13810000' WHERE LOWER(name) = LOWER('Tiquisio');
UPDATE cities SET mipaquete_code = '13836000' WHERE LOWER(name) = LOWER('Turbaco');
UPDATE cities SET mipaquete_code = '13838000' WHERE LOWER(name) = LOWER('Turbaná');
UPDATE cities SET mipaquete_code = '13873000' WHERE LOWER(name) = LOWER('Villanueva');
UPDATE cities SET mipaquete_code = '13894000' WHERE LOWER(name) = LOWER('Zambrano');
UPDATE cities SET mipaquete_code = '15001000' WHERE LOWER(name) = LOWER('Tunja');
UPDATE cities SET mipaquete_code = '15022000' WHERE LOWER(name) = LOWER('Almeida');
UPDATE cities SET mipaquete_code = '15047000' WHERE LOWER(name) = LOWER('Aquitania');
UPDATE cities SET mipaquete_code = '15051000' WHERE LOWER(name) = LOWER('Arcabuco');
UPDATE cities SET mipaquete_code = '15087000' WHERE LOWER(name) = LOWER('Belén');
UPDATE cities SET mipaquete_code = '15090000' WHERE LOWER(name) = LOWER('Berbeo');
UPDATE cities SET mipaquete_code = '15092000' WHERE LOWER(name) = LOWER('Betéitiva');
UPDATE cities SET mipaquete_code = '15097000' WHERE LOWER(name) = LOWER('Boavita');
UPDATE cities SET mipaquete_code = '15104000' WHERE LOWER(name) = LOWER('Boyacá');
UPDATE cities SET mipaquete_code = '15106000' WHERE LOWER(name) = LOWER('Briceño');
UPDATE cities SET mipaquete_code = '15109000' WHERE LOWER(name) = LOWER('Buenavista');
UPDATE cities SET mipaquete_code = '15114000' WHERE LOWER(name) = LOWER('Busbanzá');
UPDATE cities SET mipaquete_code = '15131000' WHERE LOWER(name) = LOWER('Caldas');
UPDATE cities SET mipaquete_code = '15135000' WHERE LOWER(name) = LOWER('Campohermoso');
UPDATE cities SET mipaquete_code = '15162000' WHERE LOWER(name) = LOWER('Cerinza');
UPDATE cities SET mipaquete_code = '15172000' WHERE LOWER(name) = LOWER('Chinavita');
UPDATE cities SET mipaquete_code = '15176000' WHERE LOWER(name) = LOWER('Chiquinquirá');
UPDATE cities SET mipaquete_code = '15180000' WHERE LOWER(name) = LOWER('Chiscas');
UPDATE cities SET mipaquete_code = '15183000' WHERE LOWER(name) = LOWER('Chita');
UPDATE cities SET mipaquete_code = '15185000' WHERE LOWER(name) = LOWER('Chitaraque');
UPDATE cities SET mipaquete_code = '15187000' WHERE LOWER(name) = LOWER('Chivatá');
UPDATE cities SET mipaquete_code = '15189000' WHERE LOWER(name) = LOWER('Ciénega');
UPDATE cities SET mipaquete_code = '15204000' WHERE LOWER(name) = LOWER('Cómbita');
UPDATE cities SET mipaquete_code = '15212000' WHERE LOWER(name) = LOWER('Coper');
UPDATE cities SET mipaquete_code = '15215000' WHERE LOWER(name) = LOWER('Corrales');
UPDATE cities SET mipaquete_code = '15218000' WHERE LOWER(name) = LOWER('Covarachía');
UPDATE cities SET mipaquete_code = '15223000' WHERE LOWER(name) = LOWER('Cubará');
UPDATE cities SET mipaquete_code = '15224000' WHERE LOWER(name) = LOWER('Cucaita');
UPDATE cities SET mipaquete_code = '15226000' WHERE LOWER(name) = LOWER('Cuítiva');
UPDATE cities SET mipaquete_code = '15232000' WHERE LOWER(name) = LOWER('Chíquiza');
UPDATE cities SET mipaquete_code = '15236000' WHERE LOWER(name) = LOWER('Chivor');
UPDATE cities SET mipaquete_code = '15238000' WHERE LOWER(name) = LOWER('Duitama');
UPDATE cities SET mipaquete_code = '15244000' WHERE LOWER(name) = LOWER('El Cocuy');
UPDATE cities SET mipaquete_code = '15248000' WHERE LOWER(name) = LOWER('El Espino');
UPDATE cities SET mipaquete_code = '15272000' WHERE LOWER(name) = LOWER('Firavitoba');
UPDATE cities SET mipaquete_code = '15276000' WHERE LOWER(name) = LOWER('Floresta');
UPDATE cities SET mipaquete_code = '15293000' WHERE LOWER(name) = LOWER('Gachantivá');
UPDATE cities SET mipaquete_code = '15296000' WHERE LOWER(name) = LOWER('Gámeza');
UPDATE cities SET mipaquete_code = '15299000' WHERE LOWER(name) = LOWER('Garagoa');
UPDATE cities SET mipaquete_code = '15317000' WHERE LOWER(name) = LOWER('Guacamayas');
UPDATE cities SET mipaquete_code = '15322000' WHERE LOWER(name) = LOWER('Guateque');
UPDATE cities SET mipaquete_code = '15325000' WHERE LOWER(name) = LOWER('Guayatá');
UPDATE cities SET mipaquete_code = '15332000' WHERE LOWER(name) = LOWER('Güicán De La Sierra');
UPDATE cities SET mipaquete_code = '15362000' WHERE LOWER(name) = LOWER('Iza');
UPDATE cities SET mipaquete_code = '15367000' WHERE LOWER(name) = LOWER('Jenesano');
UPDATE cities SET mipaquete_code = '15368000' WHERE LOWER(name) = LOWER('Jericó');
UPDATE cities SET mipaquete_code = '15377000' WHERE LOWER(name) = LOWER('Labranzagrande');
UPDATE cities SET mipaquete_code = '15380000' WHERE LOWER(name) = LOWER('La Capilla');
UPDATE cities SET mipaquete_code = '15401000' WHERE LOWER(name) = LOWER('La Victoria');
UPDATE cities SET mipaquete_code = '15403000' WHERE LOWER(name) = LOWER('La Uvita');
UPDATE cities SET mipaquete_code = '15407000' WHERE LOWER(name) = LOWER('Villa De Leyva');
UPDATE cities SET mipaquete_code = '15425000' WHERE LOWER(name) = LOWER('Macanal');
UPDATE cities SET mipaquete_code = '15442000' WHERE LOWER(name) = LOWER('Maripí');
UPDATE cities SET mipaquete_code = '15455000' WHERE LOWER(name) = LOWER('Miraflores');
UPDATE cities SET mipaquete_code = '15464000' WHERE LOWER(name) = LOWER('Mongua');
UPDATE cities SET mipaquete_code = '15466000' WHERE LOWER(name) = LOWER('Monguí');
UPDATE cities SET mipaquete_code = '15469000' WHERE LOWER(name) = LOWER('Moniquirá');
UPDATE cities SET mipaquete_code = '15476000' WHERE LOWER(name) = LOWER('Motavita');
UPDATE cities SET mipaquete_code = '15480000' WHERE LOWER(name) = LOWER('Muzo');
UPDATE cities SET mipaquete_code = '15491000' WHERE LOWER(name) = LOWER('Nobsa');
UPDATE cities SET mipaquete_code = '15494000' WHERE LOWER(name) = LOWER('Nuevo Colón');
UPDATE cities SET mipaquete_code = '15500000' WHERE LOWER(name) = LOWER('Oicatá');
UPDATE cities SET mipaquete_code = '15507000' WHERE LOWER(name) = LOWER('Otanche');
UPDATE cities SET mipaquete_code = '15511000' WHERE LOWER(name) = LOWER('Pachavita');
UPDATE cities SET mipaquete_code = '15514000' WHERE LOWER(name) = LOWER('Páez');
UPDATE cities SET mipaquete_code = '15516000' WHERE LOWER(name) = LOWER('Paipa');
UPDATE cities SET mipaquete_code = '15518000' WHERE LOWER(name) = LOWER('Pajarito');
UPDATE cities SET mipaquete_code = '15522000' WHERE LOWER(name) = LOWER('Panqueba');
UPDATE cities SET mipaquete_code = '15531000' WHERE LOWER(name) = LOWER('Pauna');
UPDATE cities SET mipaquete_code = '15533000' WHERE LOWER(name) = LOWER('Paya');
UPDATE cities SET mipaquete_code = '15537000' WHERE LOWER(name) = LOWER('Paz De Río');
UPDATE cities SET mipaquete_code = '15542000' WHERE LOWER(name) = LOWER('Pesca');
UPDATE cities SET mipaquete_code = '15550000' WHERE LOWER(name) = LOWER('Pisba');
UPDATE cities SET mipaquete_code = '15572000' WHERE LOWER(name) = LOWER('Puerto Boyacá');
UPDATE cities SET mipaquete_code = '15580000' WHERE LOWER(name) = LOWER('Quípama');
UPDATE cities SET mipaquete_code = '15599000' WHERE LOWER(name) = LOWER('Ramiriquí');
UPDATE cities SET mipaquete_code = '15600000' WHERE LOWER(name) = LOWER('Ráquira');
UPDATE cities SET mipaquete_code = '15621000' WHERE LOWER(name) = LOWER('Rondón');
UPDATE cities SET mipaquete_code = '15632000' WHERE LOWER(name) = LOWER('Saboyá');
UPDATE cities SET mipaquete_code = '15638000' WHERE LOWER(name) = LOWER('Sáchica');
UPDATE cities SET mipaquete_code = '15646000' WHERE LOWER(name) = LOWER('Samacá');
UPDATE cities SET mipaquete_code = '15660000' WHERE LOWER(name) = LOWER('San Eduardo');
UPDATE cities SET mipaquete_code = '15664000' WHERE LOWER(name) = LOWER('San José De Pare');
UPDATE cities SET mipaquete_code = '15667000' WHERE LOWER(name) = LOWER('San Luis De Gaceno');
UPDATE cities SET mipaquete_code = '15673000' WHERE LOWER(name) = LOWER('San Mateo');
UPDATE cities SET mipaquete_code = '15676000' WHERE LOWER(name) = LOWER('San Miguel De Sema');
UPDATE cities SET mipaquete_code = '15681000' WHERE LOWER(name) = LOWER('San Pablo De Borbur');
UPDATE cities SET mipaquete_code = '15686000' WHERE LOWER(name) = LOWER('Santana');
UPDATE cities SET mipaquete_code = '15690000' WHERE LOWER(name) = LOWER('Santa María');
UPDATE cities SET mipaquete_code = '15693000' WHERE LOWER(name) = LOWER('Santa Rosa De Viterbo');
UPDATE cities SET mipaquete_code = '15696000' WHERE LOWER(name) = LOWER('Santa Sofía');
UPDATE cities SET mipaquete_code = '15720000' WHERE LOWER(name) = LOWER('Sativanorte');
UPDATE cities SET mipaquete_code = '15723000' WHERE LOWER(name) = LOWER('Sativasur');
UPDATE cities SET mipaquete_code = '15740000' WHERE LOWER(name) = LOWER('Siachoque');
UPDATE cities SET mipaquete_code = '15753000' WHERE LOWER(name) = LOWER('Soatá');
UPDATE cities SET mipaquete_code = '15755000' WHERE LOWER(name) = LOWER('Socotá');
UPDATE cities SET mipaquete_code = '15757000' WHERE LOWER(name) = LOWER('Socha');
UPDATE cities SET mipaquete_code = '15759000' WHERE LOWER(name) = LOWER('Sogamoso');
UPDATE cities SET mipaquete_code = '15761000' WHERE LOWER(name) = LOWER('Somondoco');
UPDATE cities SET mipaquete_code = '15762000' WHERE LOWER(name) = LOWER('Sora');
UPDATE cities SET mipaquete_code = '15763000' WHERE LOWER(name) = LOWER('Sotaquirá');
UPDATE cities SET mipaquete_code = '15764000' WHERE LOWER(name) = LOWER('Soracá');
UPDATE cities SET mipaquete_code = '15774000' WHERE LOWER(name) = LOWER('Susacón');
UPDATE cities SET mipaquete_code = '15776000' WHERE LOWER(name) = LOWER('Sutamarchán');
UPDATE cities SET mipaquete_code = '15778000' WHERE LOWER(name) = LOWER('Sutatenza');
UPDATE cities SET mipaquete_code = '15790000' WHERE LOWER(name) = LOWER('Tasco');
UPDATE cities SET mipaquete_code = '15798000' WHERE LOWER(name) = LOWER('Tenza');
UPDATE cities SET mipaquete_code = '15804000' WHERE LOWER(name) = LOWER('Tibaná');
UPDATE cities SET mipaquete_code = '15806000' WHERE LOWER(name) = LOWER('Tibasosa');
UPDATE cities SET mipaquete_code = '15808000' WHERE LOWER(name) = LOWER('Tinjacá');
UPDATE cities SET mipaquete_code = '15810000' WHERE LOWER(name) = LOWER('Tipacoque');
UPDATE cities SET mipaquete_code = '15814000' WHERE LOWER(name) = LOWER('Toca');
UPDATE cities SET mipaquete_code = '15816000' WHERE LOWER(name) = LOWER('Togüí');
UPDATE cities SET mipaquete_code = '15820000' WHERE LOWER(name) = LOWER('Tópaga');
UPDATE cities SET mipaquete_code = '15822000' WHERE LOWER(name) = LOWER('Tota');
UPDATE cities SET mipaquete_code = '15832000' WHERE LOWER(name) = LOWER('Tununguá');
UPDATE cities SET mipaquete_code = '15835000' WHERE LOWER(name) = LOWER('Turmequé');
UPDATE cities SET mipaquete_code = '15837000' WHERE LOWER(name) = LOWER('Tuta');
UPDATE cities SET mipaquete_code = '15839000' WHERE LOWER(name) = LOWER('Tutazá');
UPDATE cities SET mipaquete_code = '15842000' WHERE LOWER(name) = LOWER('Úmbita');
UPDATE cities SET mipaquete_code = '15861000' WHERE LOWER(name) = LOWER('Ventaquemada');
UPDATE cities SET mipaquete_code = '15879000' WHERE LOWER(name) = LOWER('Viracachá');
UPDATE cities SET mipaquete_code = '15897000' WHERE LOWER(name) = LOWER('Zetaquira');
UPDATE cities SET mipaquete_code = '17001000' WHERE LOWER(name) = LOWER('Manizales');
UPDATE cities SET mipaquete_code = '17013000' WHERE LOWER(name) = LOWER('Aguadas');
UPDATE cities SET mipaquete_code = '17042000' WHERE LOWER(name) = LOWER('Anserma');
UPDATE cities SET mipaquete_code = '17050000' WHERE LOWER(name) = LOWER('Aranzazu');
UPDATE cities SET mipaquete_code = '17088000' WHERE LOWER(name) = LOWER('Belalcázar');
UPDATE cities SET mipaquete_code = '17174000' WHERE LOWER(name) = LOWER('Chinchiná');
UPDATE cities SET mipaquete_code = '17272000' WHERE LOWER(name) = LOWER('Filadelfia');
UPDATE cities SET mipaquete_code = '17380000' WHERE LOWER(name) = LOWER('La Dorada');
UPDATE cities SET mipaquete_code = '17388000' WHERE LOWER(name) = LOWER('La Merced');
UPDATE cities SET mipaquete_code = '17433000' WHERE LOWER(name) = LOWER('Manzanares');
UPDATE cities SET mipaquete_code = '17442000' WHERE LOWER(name) = LOWER('Marmato');
UPDATE cities SET mipaquete_code = '17444000' WHERE LOWER(name) = LOWER('Marquetalia');
UPDATE cities SET mipaquete_code = '17446000' WHERE LOWER(name) = LOWER('Marulanda');
UPDATE cities SET mipaquete_code = '17486000' WHERE LOWER(name) = LOWER('Neira');
UPDATE cities SET mipaquete_code = '17495000' WHERE LOWER(name) = LOWER('Norcasia');
UPDATE cities SET mipaquete_code = '17513000' WHERE LOWER(name) = LOWER('Pácora');
UPDATE cities SET mipaquete_code = '17524000' WHERE LOWER(name) = LOWER('Palestina');
UPDATE cities SET mipaquete_code = '17541000' WHERE LOWER(name) = LOWER('Pensilvania');
UPDATE cities SET mipaquete_code = '17614000' WHERE LOWER(name) = LOWER('Riosucio');
UPDATE cities SET mipaquete_code = '17616000' WHERE LOWER(name) = LOWER('Risaralda');
UPDATE cities SET mipaquete_code = '17653000' WHERE LOWER(name) = LOWER('Salamina');
UPDATE cities SET mipaquete_code = '17662000' WHERE LOWER(name) = LOWER('Samaná');
UPDATE cities SET mipaquete_code = '17665000' WHERE LOWER(name) = LOWER('San José');
UPDATE cities SET mipaquete_code = '17777000' WHERE LOWER(name) = LOWER('Supía');
UPDATE cities SET mipaquete_code = '17867000' WHERE LOWER(name) = LOWER('Victoria');
UPDATE cities SET mipaquete_code = '17873000' WHERE LOWER(name) = LOWER('Villamaría');
UPDATE cities SET mipaquete_code = '17877000' WHERE LOWER(name) = LOWER('Viterbo');
UPDATE cities SET mipaquete_code = '18001000' WHERE LOWER(name) = LOWER('Florencia');
UPDATE cities SET mipaquete_code = '18029000' WHERE LOWER(name) = LOWER('Albania');
UPDATE cities SET mipaquete_code = '18094000' WHERE LOWER(name) = LOWER('Belén De Los Andaquíes');
UPDATE cities SET mipaquete_code = '18150000' WHERE LOWER(name) = LOWER('Cartagena Del Chairá');
UPDATE cities SET mipaquete_code = '18205000' WHERE LOWER(name) = LOWER('Curillo');
UPDATE cities SET mipaquete_code = '18247000' WHERE LOWER(name) = LOWER('El Doncello');
UPDATE cities SET mipaquete_code = '18256000' WHERE LOWER(name) = LOWER('El Paujíl');
UPDATE cities SET mipaquete_code = '18410000' WHERE LOWER(name) = LOWER('La Montañita');
UPDATE cities SET mipaquete_code = '18460000' WHERE LOWER(name) = LOWER('Milán');
UPDATE cities SET mipaquete_code = '18479000' WHERE LOWER(name) = LOWER('Morelia');
UPDATE cities SET mipaquete_code = '18592000' WHERE LOWER(name) = LOWER('Puerto Rico');
UPDATE cities SET mipaquete_code = '18610000' WHERE LOWER(name) = LOWER('San José Del Fragua');
UPDATE cities SET mipaquete_code = '18753000' WHERE LOWER(name) = LOWER('San Vicente Del Caguán');
UPDATE cities SET mipaquete_code = '18756000' WHERE LOWER(name) = LOWER('Solano');
UPDATE cities SET mipaquete_code = '18785000' WHERE LOWER(name) = LOWER('Solita');
UPDATE cities SET mipaquete_code = '18860000' WHERE LOWER(name) = LOWER('Valparaíso');
UPDATE cities SET mipaquete_code = '19001000' WHERE LOWER(name) = LOWER('Popayán');
UPDATE cities SET mipaquete_code = '19022000' WHERE LOWER(name) = LOWER('Almaguer');
UPDATE cities SET mipaquete_code = '19050000' WHERE LOWER(name) = LOWER('Argelia');
UPDATE cities SET mipaquete_code = '19075000' WHERE LOWER(name) = LOWER('Balboa');
UPDATE cities SET mipaquete_code = '19100000' WHERE LOWER(name) = LOWER('Bolívar');
UPDATE cities SET mipaquete_code = '19110000' WHERE LOWER(name) = LOWER('Buenos Aires');
UPDATE cities SET mipaquete_code = '19130000' WHERE LOWER(name) = LOWER('Cajibío');
UPDATE cities SET mipaquete_code = '19137000' WHERE LOWER(name) = LOWER('Caldono');
UPDATE cities SET mipaquete_code = '19142000' WHERE LOWER(name) = LOWER('Caloto');
UPDATE cities SET mipaquete_code = '19212000' WHERE LOWER(name) = LOWER('Corinto');
UPDATE cities SET mipaquete_code = '19256000' WHERE LOWER(name) = LOWER('El Tambo');
UPDATE cities SET mipaquete_code = '19290000' WHERE LOWER(name) = LOWER('Florencia');
UPDATE cities SET mipaquete_code = '19300000' WHERE LOWER(name) = LOWER('Guachené');
UPDATE cities SET mipaquete_code = '19318000' WHERE LOWER(name) = LOWER('Guapi');
UPDATE cities SET mipaquete_code = '19355000' WHERE LOWER(name) = LOWER('Inzá');
UPDATE cities SET mipaquete_code = '19364000' WHERE LOWER(name) = LOWER('Jambaló');
UPDATE cities SET mipaquete_code = '19392000' WHERE LOWER(name) = LOWER('La Sierra');
UPDATE cities SET mipaquete_code = '19397000' WHERE LOWER(name) = LOWER('La Vega');
UPDATE cities SET mipaquete_code = '19418000' WHERE LOWER(name) = LOWER('López De Micay');
UPDATE cities SET mipaquete_code = '19450000' WHERE LOWER(name) = LOWER('Mercaderes');
UPDATE cities SET mipaquete_code = '19455000' WHERE LOWER(name) = LOWER('Miranda');
UPDATE cities SET mipaquete_code = '19473000' WHERE LOWER(name) = LOWER('Morales');
UPDATE cities SET mipaquete_code = '19513000' WHERE LOWER(name) = LOWER('Padilla');
UPDATE cities SET mipaquete_code = '19517000' WHERE LOWER(name) = LOWER('Páez');
UPDATE cities SET mipaquete_code = '19532000' WHERE LOWER(name) = LOWER('Patía');
UPDATE cities SET mipaquete_code = '19533000' WHERE LOWER(name) = LOWER('Piamonte');
UPDATE cities SET mipaquete_code = '19548000' WHERE LOWER(name) = LOWER('Piendamó - Tunía');
UPDATE cities SET mipaquete_code = '19573000' WHERE LOWER(name) = LOWER('Puerto Tejada');
UPDATE cities SET mipaquete_code = '19585000' WHERE LOWER(name) = LOWER('Puracé');
UPDATE cities SET mipaquete_code = '19622000' WHERE LOWER(name) = LOWER('Rosas');
UPDATE cities SET mipaquete_code = '19693000' WHERE LOWER(name) = LOWER('San Sebastián');
UPDATE cities SET mipaquete_code = '19698000' WHERE LOWER(name) = LOWER('Santander De Quilichao');
UPDATE cities SET mipaquete_code = '19701000' WHERE LOWER(name) = LOWER('Santa Rosa');
UPDATE cities SET mipaquete_code = '19743000' WHERE LOWER(name) = LOWER('Silvia');
UPDATE cities SET mipaquete_code = '19760000' WHERE LOWER(name) = LOWER('Sotará - Paispamba');
UPDATE cities SET mipaquete_code = '19780000' WHERE LOWER(name) = LOWER('Suárez');
UPDATE cities SET mipaquete_code = '19785000' WHERE LOWER(name) = LOWER('Sucre');
UPDATE cities SET mipaquete_code = '19807000' WHERE LOWER(name) = LOWER('Timbío');
UPDATE cities SET mipaquete_code = '19809000' WHERE LOWER(name) = LOWER('Timbiquí');
UPDATE cities SET mipaquete_code = '19821000' WHERE LOWER(name) = LOWER('Toribío');
UPDATE cities SET mipaquete_code = '19824000' WHERE LOWER(name) = LOWER('Totoró');
UPDATE cities SET mipaquete_code = '19845000' WHERE LOWER(name) = LOWER('Villa Rica');
UPDATE cities SET mipaquete_code = '20001000' WHERE LOWER(name) = LOWER('Valledupar');
UPDATE cities SET mipaquete_code = '20011000' WHERE LOWER(name) = LOWER('Aguachica');
UPDATE cities SET mipaquete_code = '20013000' WHERE LOWER(name) = LOWER('Agustín Codazzi');
UPDATE cities SET mipaquete_code = '20032000' WHERE LOWER(name) = LOWER('Astrea');
UPDATE cities SET mipaquete_code = '20045000' WHERE LOWER(name) = LOWER('Becerril');
UPDATE cities SET mipaquete_code = '20060000' WHERE LOWER(name) = LOWER('Bosconia');
UPDATE cities SET mipaquete_code = '20175000' WHERE LOWER(name) = LOWER('Chimichagua');
UPDATE cities SET mipaquete_code = '20178000' WHERE LOWER(name) = LOWER('Chiriguaná');
UPDATE cities SET mipaquete_code = '20228000' WHERE LOWER(name) = LOWER('Curumaní');
UPDATE cities SET mipaquete_code = '20238000' WHERE LOWER(name) = LOWER('El Copey');
UPDATE cities SET mipaquete_code = '20250000' WHERE LOWER(name) = LOWER('El Paso');
UPDATE cities SET mipaquete_code = '20295000' WHERE LOWER(name) = LOWER('Gamarra');
UPDATE cities SET mipaquete_code = '20310000' WHERE LOWER(name) = LOWER('González');
UPDATE cities SET mipaquete_code = '20383000' WHERE LOWER(name) = LOWER('La Gloria');
UPDATE cities SET mipaquete_code = '20400000' WHERE LOWER(name) = LOWER('La Jagua De Ibirico');
UPDATE cities SET mipaquete_code = '20443000' WHERE LOWER(name) = LOWER('Manaure Balcón Del Cesar');
UPDATE cities SET mipaquete_code = '20517000' WHERE LOWER(name) = LOWER('Pailitas');
UPDATE cities SET mipaquete_code = '20550000' WHERE LOWER(name) = LOWER('Pelaya');
UPDATE cities SET mipaquete_code = '20570000' WHERE LOWER(name) = LOWER('Pueblo Bello');
UPDATE cities SET mipaquete_code = '20614000' WHERE LOWER(name) = LOWER('Río De Oro');
UPDATE cities SET mipaquete_code = '20621000' WHERE LOWER(name) = LOWER('La Paz');
UPDATE cities SET mipaquete_code = '20710000' WHERE LOWER(name) = LOWER('San Alberto');
UPDATE cities SET mipaquete_code = '20750000' WHERE LOWER(name) = LOWER('San Diego');
UPDATE cities SET mipaquete_code = '20770000' WHERE LOWER(name) = LOWER('San Martín');
UPDATE cities SET mipaquete_code = '20787000' WHERE LOWER(name) = LOWER('Tamalameque');
UPDATE cities SET mipaquete_code = '23001000' WHERE LOWER(name) = LOWER('Montería');
UPDATE cities SET mipaquete_code = '23068000' WHERE LOWER(name) = LOWER('Ayapel');
UPDATE cities SET mipaquete_code = '23079000' WHERE LOWER(name) = LOWER('Buenavista');
UPDATE cities SET mipaquete_code = '23090000' WHERE LOWER(name) = LOWER('Canalete');
UPDATE cities SET mipaquete_code = '23162000' WHERE LOWER(name) = LOWER('Cereté');
UPDATE cities SET mipaquete_code = '23168000' WHERE LOWER(name) = LOWER('Chimá');
UPDATE cities SET mipaquete_code = '23182000' WHERE LOWER(name) = LOWER('Chinú');
UPDATE cities SET mipaquete_code = '23189000' WHERE LOWER(name) = LOWER('Ciénaga De Oro');
UPDATE cities SET mipaquete_code = '23300000' WHERE LOWER(name) = LOWER('Cotorra');
UPDATE cities SET mipaquete_code = '23350000' WHERE LOWER(name) = LOWER('La Apartada');
UPDATE cities SET mipaquete_code = '23417000' WHERE LOWER(name) = LOWER('Lorica');
UPDATE cities SET mipaquete_code = '23419000' WHERE LOWER(name) = LOWER('Los Córdobas');
UPDATE cities SET mipaquete_code = '23464000' WHERE LOWER(name) = LOWER('Momil');
UPDATE cities SET mipaquete_code = '23466000' WHERE LOWER(name) = LOWER('Montelíbano');
UPDATE cities SET mipaquete_code = '23500000' WHERE LOWER(name) = LOWER('Moñitos');
UPDATE cities SET mipaquete_code = '23555000' WHERE LOWER(name) = LOWER('Planeta Rica');
UPDATE cities SET mipaquete_code = '23570000' WHERE LOWER(name) = LOWER('Pueblo Nuevo');
UPDATE cities SET mipaquete_code = '23574000' WHERE LOWER(name) = LOWER('Puerto Escondido');
UPDATE cities SET mipaquete_code = '23580000' WHERE LOWER(name) = LOWER('Puerto Libertador');
UPDATE cities SET mipaquete_code = '23586000' WHERE LOWER(name) = LOWER('Purísima De La Concepción');
UPDATE cities SET mipaquete_code = '23660000' WHERE LOWER(name) = LOWER('Sahagún');
UPDATE cities SET mipaquete_code = '23670000' WHERE LOWER(name) = LOWER('San Andrés De Sotavento');
UPDATE cities SET mipaquete_code = '23672000' WHERE LOWER(name) = LOWER('San Antero');
UPDATE cities SET mipaquete_code = '23675000' WHERE LOWER(name) = LOWER('San Bernardo Del Viento');
UPDATE cities SET mipaquete_code = '23678000' WHERE LOWER(name) = LOWER('San Carlos');
UPDATE cities SET mipaquete_code = '23682000' WHERE LOWER(name) = LOWER('San José De Uré');
UPDATE cities SET mipaquete_code = '23686000' WHERE LOWER(name) = LOWER('San Pelayo');
UPDATE cities SET mipaquete_code = '23807000' WHERE LOWER(name) = LOWER('Tierralta');
UPDATE cities SET mipaquete_code = '23815000' WHERE LOWER(name) = LOWER('Tuchín');
UPDATE cities SET mipaquete_code = '23855000' WHERE LOWER(name) = LOWER('Valencia');
UPDATE cities SET mipaquete_code = '25001000' WHERE LOWER(name) = LOWER('Agua De Dios');
UPDATE cities SET mipaquete_code = '25019000' WHERE LOWER(name) = LOWER('Albán');
UPDATE cities SET mipaquete_code = '25035000' WHERE LOWER(name) = LOWER('Anapoima');
UPDATE cities SET mipaquete_code = '25040000' WHERE LOWER(name) = LOWER('Anolaima');
UPDATE cities SET mipaquete_code = '25053000' WHERE LOWER(name) = LOWER('Arbeláez');
UPDATE cities SET mipaquete_code = '25086000' WHERE LOWER(name) = LOWER('Beltrán');
UPDATE cities SET mipaquete_code = '25095000' WHERE LOWER(name) = LOWER('Bituima');
UPDATE cities SET mipaquete_code = '25099000' WHERE LOWER(name) = LOWER('Bojacá');
UPDATE cities SET mipaquete_code = '25120000' WHERE LOWER(name) = LOWER('Cabrera');
UPDATE cities SET mipaquete_code = '25123000' WHERE LOWER(name) = LOWER('Cachipay');
UPDATE cities SET mipaquete_code = '25126000' WHERE LOWER(name) = LOWER('Cajicá');
UPDATE cities SET mipaquete_code = '25148000' WHERE LOWER(name) = LOWER('Caparrapí');
UPDATE cities SET mipaquete_code = '25151000' WHERE LOWER(name) = LOWER('Cáqueza');
UPDATE cities SET mipaquete_code = '25154000' WHERE LOWER(name) = LOWER('Carmen De Carupa');
UPDATE cities SET mipaquete_code = '25168000' WHERE LOWER(name) = LOWER('Chaguaní');
UPDATE cities SET mipaquete_code = '25175000' WHERE LOWER(name) = LOWER('Chía');
UPDATE cities SET mipaquete_code = '25178000' WHERE LOWER(name) = LOWER('Chipaque');
UPDATE cities SET mipaquete_code = '25181000' WHERE LOWER(name) = LOWER('Choachí');
UPDATE cities SET mipaquete_code = '25183000' WHERE LOWER(name) = LOWER('Chocontá');
UPDATE cities SET mipaquete_code = '25200000' WHERE LOWER(name) = LOWER('Cogua');
UPDATE cities SET mipaquete_code = '25214000' WHERE LOWER(name) = LOWER('Cota');
UPDATE cities SET mipaquete_code = '25224000' WHERE LOWER(name) = LOWER('Cucunubá');
UPDATE cities SET mipaquete_code = '25245000' WHERE LOWER(name) = LOWER('El Colegio');
UPDATE cities SET mipaquete_code = '25258000' WHERE LOWER(name) = LOWER('El Peñón');
UPDATE cities SET mipaquete_code = '25260000' WHERE LOWER(name) = LOWER('El Rosal');
UPDATE cities SET mipaquete_code = '25269000' WHERE LOWER(name) = LOWER('Facatativá');
UPDATE cities SET mipaquete_code = '25279000' WHERE LOWER(name) = LOWER('Fómeque');
UPDATE cities SET mipaquete_code = '25281000' WHERE LOWER(name) = LOWER('Fosca');
UPDATE cities SET mipaquete_code = '25286000' WHERE LOWER(name) = LOWER('Funza');
UPDATE cities SET mipaquete_code = '25288000' WHERE LOWER(name) = LOWER('Fúquene');
UPDATE cities SET mipaquete_code = '25290000' WHERE LOWER(name) = LOWER('Fusagasugá');
UPDATE cities SET mipaquete_code = '25293000' WHERE LOWER(name) = LOWER('Gachalá');
UPDATE cities SET mipaquete_code = '25295000' WHERE LOWER(name) = LOWER('Gachancipá');
UPDATE cities SET mipaquete_code = '25297000' WHERE LOWER(name) = LOWER('Gachetá');
UPDATE cities SET mipaquete_code = '25299000' WHERE LOWER(name) = LOWER('Gama');
UPDATE cities SET mipaquete_code = '25307000' WHERE LOWER(name) = LOWER('Girardot');
UPDATE cities SET mipaquete_code = '25312000' WHERE LOWER(name) = LOWER('Granada');
UPDATE cities SET mipaquete_code = '25317000' WHERE LOWER(name) = LOWER('Guachetá');
UPDATE cities SET mipaquete_code = '25320000' WHERE LOWER(name) = LOWER('Guaduas');
UPDATE cities SET mipaquete_code = '25322000' WHERE LOWER(name) = LOWER('Guasca');
UPDATE cities SET mipaquete_code = '25324000' WHERE LOWER(name) = LOWER('Guataquí');
UPDATE cities SET mipaquete_code = '25326000' WHERE LOWER(name) = LOWER('Guatavita');
UPDATE cities SET mipaquete_code = '25328000' WHERE LOWER(name) = LOWER('Guayabal De Síquima');
UPDATE cities SET mipaquete_code = '25335000' WHERE LOWER(name) = LOWER('Guayabetal');
UPDATE cities SET mipaquete_code = '25339000' WHERE LOWER(name) = LOWER('Gutiérrez');
UPDATE cities SET mipaquete_code = '25368000' WHERE LOWER(name) = LOWER('Jerusalén');
UPDATE cities SET mipaquete_code = '25372000' WHERE LOWER(name) = LOWER('Junín');
UPDATE cities SET mipaquete_code = '25377000' WHERE LOWER(name) = LOWER('La Calera');
UPDATE cities SET mipaquete_code = '25386000' WHERE LOWER(name) = LOWER('La Mesa');
UPDATE cities SET mipaquete_code = '25394000' WHERE LOWER(name) = LOWER('La Palma');
UPDATE cities SET mipaquete_code = '25398000' WHERE LOWER(name) = LOWER('La Peña');
UPDATE cities SET mipaquete_code = '25402000' WHERE LOWER(name) = LOWER('La Vega');
UPDATE cities SET mipaquete_code = '25407000' WHERE LOWER(name) = LOWER('Lenguazaque');
UPDATE cities SET mipaquete_code = '25426000' WHERE LOWER(name) = LOWER('Machetá');
UPDATE cities SET mipaquete_code = '25430000' WHERE LOWER(name) = LOWER('Madrid');
UPDATE cities SET mipaquete_code = '25436000' WHERE LOWER(name) = LOWER('Manta');
UPDATE cities SET mipaquete_code = '25438000' WHERE LOWER(name) = LOWER('Medina');
UPDATE cities SET mipaquete_code = '25473000' WHERE LOWER(name) = LOWER('Mosquera');
UPDATE cities SET mipaquete_code = '25483000' WHERE LOWER(name) = LOWER('Nariño');
UPDATE cities SET mipaquete_code = '25486000' WHERE LOWER(name) = LOWER('Nemocón');
UPDATE cities SET mipaquete_code = '25488000' WHERE LOWER(name) = LOWER('Nilo');
UPDATE cities SET mipaquete_code = '25489000' WHERE LOWER(name) = LOWER('Nimaima');
UPDATE cities SET mipaquete_code = '25491000' WHERE LOWER(name) = LOWER('Nocaima');
UPDATE cities SET mipaquete_code = '25506000' WHERE LOWER(name) = LOWER('Venecia');
UPDATE cities SET mipaquete_code = '25513000' WHERE LOWER(name) = LOWER('Pacho');
UPDATE cities SET mipaquete_code = '25518000' WHERE LOWER(name) = LOWER('Paime');
UPDATE cities SET mipaquete_code = '25524000' WHERE LOWER(name) = LOWER('Pandi');
UPDATE cities SET mipaquete_code = '25530000' WHERE LOWER(name) = LOWER('Paratebueno');
UPDATE cities SET mipaquete_code = '25535000' WHERE LOWER(name) = LOWER('Pasca');
UPDATE cities SET mipaquete_code = '25572000' WHERE LOWER(name) = LOWER('Puerto Salgar');
UPDATE cities SET mipaquete_code = '25580000' WHERE LOWER(name) = LOWER('Pulí');
UPDATE cities SET mipaquete_code = '25592000' WHERE LOWER(name) = LOWER('Quebradanegra');
UPDATE cities SET mipaquete_code = '25594000' WHERE LOWER(name) = LOWER('Quetame');
UPDATE cities SET mipaquete_code = '25596000' WHERE LOWER(name) = LOWER('Quipile');
UPDATE cities SET mipaquete_code = '25599000' WHERE LOWER(name) = LOWER('Apulo');
UPDATE cities SET mipaquete_code = '25612000' WHERE LOWER(name) = LOWER('Ricaurte');
UPDATE cities SET mipaquete_code = '25645000' WHERE LOWER(name) = LOWER('San Antonio Del Tequendama');
UPDATE cities SET mipaquete_code = '25649000' WHERE LOWER(name) = LOWER('San Bernardo');
UPDATE cities SET mipaquete_code = '25653000' WHERE LOWER(name) = LOWER('San Cayetano');
UPDATE cities SET mipaquete_code = '25658000' WHERE LOWER(name) = LOWER('San Francisco');
UPDATE cities SET mipaquete_code = '25662000' WHERE LOWER(name) = LOWER('San Juan De Rioseco');
UPDATE cities SET mipaquete_code = '25718000' WHERE LOWER(name) = LOWER('Sasaima');
UPDATE cities SET mipaquete_code = '25736000' WHERE LOWER(name) = LOWER('Sesquilé');
UPDATE cities SET mipaquete_code = '25740000' WHERE LOWER(name) = LOWER('Sibaté');
UPDATE cities SET mipaquete_code = '25743000' WHERE LOWER(name) = LOWER('Silvania');
UPDATE cities SET mipaquete_code = '25745000' WHERE LOWER(name) = LOWER('Simijaca');
UPDATE cities SET mipaquete_code = '25754000' WHERE LOWER(name) = LOWER('Soacha');
UPDATE cities SET mipaquete_code = '25758000' WHERE LOWER(name) = LOWER('Sopó');
UPDATE cities SET mipaquete_code = '25769000' WHERE LOWER(name) = LOWER('Subachoque');
UPDATE cities SET mipaquete_code = '25772000' WHERE LOWER(name) = LOWER('Suesca');
UPDATE cities SET mipaquete_code = '25777000' WHERE LOWER(name) = LOWER('Supatá');
UPDATE cities SET mipaquete_code = '25779000' WHERE LOWER(name) = LOWER('Susa');
UPDATE cities SET mipaquete_code = '25781000' WHERE LOWER(name) = LOWER('Sutatausa');
UPDATE cities SET mipaquete_code = '25785000' WHERE LOWER(name) = LOWER('Tabio');
UPDATE cities SET mipaquete_code = '25793000' WHERE LOWER(name) = LOWER('Tausa');
UPDATE cities SET mipaquete_code = '25797000' WHERE LOWER(name) = LOWER('Tena');
UPDATE cities SET mipaquete_code = '25799000' WHERE LOWER(name) = LOWER('Tenjo');
UPDATE cities SET mipaquete_code = '25805000' WHERE LOWER(name) = LOWER('Tibacuy');
UPDATE cities SET mipaquete_code = '25807000' WHERE LOWER(name) = LOWER('Tibirita');
UPDATE cities SET mipaquete_code = '25815000' WHERE LOWER(name) = LOWER('Tocaima');
UPDATE cities SET mipaquete_code = '25817000' WHERE LOWER(name) = LOWER('Tocancipá');
UPDATE cities SET mipaquete_code = '25823000' WHERE LOWER(name) = LOWER('Topaipí');
UPDATE cities SET mipaquete_code = '25839000' WHERE LOWER(name) = LOWER('Ubalá');
UPDATE cities SET mipaquete_code = '25841000' WHERE LOWER(name) = LOWER('Ubaque');
UPDATE cities SET mipaquete_code = '25843000' WHERE LOWER(name) = LOWER('Villa De San Diego De Ubaté');
UPDATE cities SET mipaquete_code = '25845000' WHERE LOWER(name) = LOWER('Une');
UPDATE cities SET mipaquete_code = '25851000' WHERE LOWER(name) = LOWER('Útica');
UPDATE cities SET mipaquete_code = '25862000' WHERE LOWER(name) = LOWER('Vergara');
UPDATE cities SET mipaquete_code = '25867000' WHERE LOWER(name) = LOWER('Vianí');
UPDATE cities SET mipaquete_code = '25871000' WHERE LOWER(name) = LOWER('Villagómez');
UPDATE cities SET mipaquete_code = '25873000' WHERE LOWER(name) = LOWER('Villapinzón');
UPDATE cities SET mipaquete_code = '25875000' WHERE LOWER(name) = LOWER('Villeta');
UPDATE cities SET mipaquete_code = '25878000' WHERE LOWER(name) = LOWER('Viotá');
UPDATE cities SET mipaquete_code = '25885000' WHERE LOWER(name) = LOWER('Yacopí');
UPDATE cities SET mipaquete_code = '25898000' WHERE LOWER(name) = LOWER('Zipacón');
UPDATE cities SET mipaquete_code = '25899000' WHERE LOWER(name) = LOWER('Zipaquirá');
UPDATE cities SET mipaquete_code = '27001000' WHERE LOWER(name) = LOWER('Quibdó');
UPDATE cities SET mipaquete_code = '27006000' WHERE LOWER(name) = LOWER('Acandí');
UPDATE cities SET mipaquete_code = '27025000' WHERE LOWER(name) = LOWER('Alto Baudó');
UPDATE cities SET mipaquete_code = '27050000' WHERE LOWER(name) = LOWER('Atrato');
UPDATE cities SET mipaquete_code = '27073000' WHERE LOWER(name) = LOWER('Bagadó');
UPDATE cities SET mipaquete_code = '27075000' WHERE LOWER(name) = LOWER('Bahía Solano');
UPDATE cities SET mipaquete_code = '27077000' WHERE LOWER(name) = LOWER('Bajo Baudó');
UPDATE cities SET mipaquete_code = '27099000' WHERE LOWER(name) = LOWER('Bojayá');
UPDATE cities SET mipaquete_code = '27135000' WHERE LOWER(name) = LOWER('El Cantón Del San Pablo');
UPDATE cities SET mipaquete_code = '27150000' WHERE LOWER(name) = LOWER('Carmen Del Darién');
UPDATE cities SET mipaquete_code = '27160000' WHERE LOWER(name) = LOWER('Cértegui');
UPDATE cities SET mipaquete_code = '27205000' WHERE LOWER(name) = LOWER('Condoto');
UPDATE cities SET mipaquete_code = '27245000' WHERE LOWER(name) = LOWER('El Carmen De Atrato');
UPDATE cities SET mipaquete_code = '27250000' WHERE LOWER(name) = LOWER('El Litoral Del San Juan');
UPDATE cities SET mipaquete_code = '27361000' WHERE LOWER(name) = LOWER('Istmina');
UPDATE cities SET mipaquete_code = '27372000' WHERE LOWER(name) = LOWER('Juradó');
UPDATE cities SET mipaquete_code = '27413000' WHERE LOWER(name) = LOWER('Lloró');
UPDATE cities SET mipaquete_code = '27425000' WHERE LOWER(name) = LOWER('Medio Atrato');
UPDATE cities SET mipaquete_code = '27430000' WHERE LOWER(name) = LOWER('Medio Baudó');
UPDATE cities SET mipaquete_code = '27450000' WHERE LOWER(name) = LOWER('Medio San Juan');
UPDATE cities SET mipaquete_code = '27491000' WHERE LOWER(name) = LOWER('Nóvita');
UPDATE cities SET mipaquete_code = '27493000' WHERE LOWER(name) = LOWER('Nuevo Belén De Bajirá');
UPDATE cities SET mipaquete_code = '27495000' WHERE LOWER(name) = LOWER('Nuquí');
UPDATE cities SET mipaquete_code = '27580000' WHERE LOWER(name) = LOWER('Río Iró');
UPDATE cities SET mipaquete_code = '27600000' WHERE LOWER(name) = LOWER('Río Quito');
UPDATE cities SET mipaquete_code = '27615000' WHERE LOWER(name) = LOWER('Riosucio');
UPDATE cities SET mipaquete_code = '27660000' WHERE LOWER(name) = LOWER('San José Del Palmar');
UPDATE cities SET mipaquete_code = '27745000' WHERE LOWER(name) = LOWER('Sipí');
UPDATE cities SET mipaquete_code = '27787000' WHERE LOWER(name) = LOWER('Tadó');
UPDATE cities SET mipaquete_code = '27800000' WHERE LOWER(name) = LOWER('Unguía');
UPDATE cities SET mipaquete_code = '27810000' WHERE LOWER(name) = LOWER('Unión Panamericana');
UPDATE cities SET mipaquete_code = '41001000' WHERE LOWER(name) = LOWER('Neiva');
UPDATE cities SET mipaquete_code = '41006000' WHERE LOWER(name) = LOWER('Acevedo');
UPDATE cities SET mipaquete_code = '41013000' WHERE LOWER(name) = LOWER('Agrado');
UPDATE cities SET mipaquete_code = '41016000' WHERE LOWER(name) = LOWER('Aipe');
UPDATE cities SET mipaquete_code = '41020000' WHERE LOWER(name) = LOWER('Algeciras');
UPDATE cities SET mipaquete_code = '41026000' WHERE LOWER(name) = LOWER('Altamira');
UPDATE cities SET mipaquete_code = '41078000' WHERE LOWER(name) = LOWER('Baraya');
UPDATE cities SET mipaquete_code = '41132000' WHERE LOWER(name) = LOWER('Campoalegre');
UPDATE cities SET mipaquete_code = '41206000' WHERE LOWER(name) = LOWER('Colombia');
UPDATE cities SET mipaquete_code = '41244000' WHERE LOWER(name) = LOWER('Elías');
UPDATE cities SET mipaquete_code = '41298000' WHERE LOWER(name) = LOWER('Garzón');
UPDATE cities SET mipaquete_code = '41306000' WHERE LOWER(name) = LOWER('Gigante');
UPDATE cities SET mipaquete_code = '41319000' WHERE LOWER(name) = LOWER('Guadalupe');
UPDATE cities SET mipaquete_code = '41349000' WHERE LOWER(name) = LOWER('Hobo');
UPDATE cities SET mipaquete_code = '41357000' WHERE LOWER(name) = LOWER('Íquira');
UPDATE cities SET mipaquete_code = '41359000' WHERE LOWER(name) = LOWER('Isnos');
UPDATE cities SET mipaquete_code = '41378000' WHERE LOWER(name) = LOWER('La Argentina');
UPDATE cities SET mipaquete_code = '41396000' WHERE LOWER(name) = LOWER('La Plata');
UPDATE cities SET mipaquete_code = '41483000' WHERE LOWER(name) = LOWER('Nátaga');
UPDATE cities SET mipaquete_code = '41503000' WHERE LOWER(name) = LOWER('Oporapa');
UPDATE cities SET mipaquete_code = '41518000' WHERE LOWER(name) = LOWER('Paicol');
UPDATE cities SET mipaquete_code = '41524000' WHERE LOWER(name) = LOWER('Palermo');
UPDATE cities SET mipaquete_code = '41530000' WHERE LOWER(name) = LOWER('Palestina');
UPDATE cities SET mipaquete_code = '41548000' WHERE LOWER(name) = LOWER('Pital');
UPDATE cities SET mipaquete_code = '41551000' WHERE LOWER(name) = LOWER('Pitalito');
UPDATE cities SET mipaquete_code = '41615000' WHERE LOWER(name) = LOWER('Rivera');
UPDATE cities SET mipaquete_code = '41660000' WHERE LOWER(name) = LOWER('Saladoblanco');
UPDATE cities SET mipaquete_code = '41668000' WHERE LOWER(name) = LOWER('San Agustín');
UPDATE cities SET mipaquete_code = '41676000' WHERE LOWER(name) = LOWER('Santa María');
UPDATE cities SET mipaquete_code = '41770000' WHERE LOWER(name) = LOWER('Suaza');
UPDATE cities SET mipaquete_code = '41791000' WHERE LOWER(name) = LOWER('Tarqui');
UPDATE cities SET mipaquete_code = '41797000' WHERE LOWER(name) = LOWER('Tesalia');
UPDATE cities SET mipaquete_code = '41799000' WHERE LOWER(name) = LOWER('Tello');
UPDATE cities SET mipaquete_code = '41801000' WHERE LOWER(name) = LOWER('Teruel');
UPDATE cities SET mipaquete_code = '41807000' WHERE LOWER(name) = LOWER('Timaná');
UPDATE cities SET mipaquete_code = '41872000' WHERE LOWER(name) = LOWER('Villavieja');
UPDATE cities SET mipaquete_code = '41885000' WHERE LOWER(name) = LOWER('Yaguará');
UPDATE cities SET mipaquete_code = '44001000' WHERE LOWER(name) = LOWER('Riohacha');
UPDATE cities SET mipaquete_code = '44035000' WHERE LOWER(name) = LOWER('Albania');
UPDATE cities SET mipaquete_code = '44078000' WHERE LOWER(name) = LOWER('Barrancas');
UPDATE cities SET mipaquete_code = '44090000' WHERE LOWER(name) = LOWER('Dibulla');
UPDATE cities SET mipaquete_code = '44098000' WHERE LOWER(name) = LOWER('Distracción');
UPDATE cities SET mipaquete_code = '44110000' WHERE LOWER(name) = LOWER('El Molino');
UPDATE cities SET mipaquete_code = '44279000' WHERE LOWER(name) = LOWER('Fonseca');
UPDATE cities SET mipaquete_code = '44378000' WHERE LOWER(name) = LOWER('Hatonuevo');
UPDATE cities SET mipaquete_code = '44420000' WHERE LOWER(name) = LOWER('La Jagua Del Pilar');
UPDATE cities SET mipaquete_code = '44430000' WHERE LOWER(name) = LOWER('Maicao');
UPDATE cities SET mipaquete_code = '44560000' WHERE LOWER(name) = LOWER('Manaure');
UPDATE cities SET mipaquete_code = '44650000' WHERE LOWER(name) = LOWER('San Juan Del Cesar');
UPDATE cities SET mipaquete_code = '44847000' WHERE LOWER(name) = LOWER('Uribia');
UPDATE cities SET mipaquete_code = '44855000' WHERE LOWER(name) = LOWER('Urumita');
UPDATE cities SET mipaquete_code = '44874000' WHERE LOWER(name) = LOWER('Villanueva');
UPDATE cities SET mipaquete_code = '47001000' WHERE LOWER(name) = LOWER('Santa Marta');
UPDATE cities SET mipaquete_code = '47030000' WHERE LOWER(name) = LOWER('Algarrobo');
UPDATE cities SET mipaquete_code = '47053000' WHERE LOWER(name) = LOWER('Aracataca');
UPDATE cities SET mipaquete_code = '47058000' WHERE LOWER(name) = LOWER('Ariguaní');
UPDATE cities SET mipaquete_code = '47161000' WHERE LOWER(name) = LOWER('Cerro De San Antonio');
UPDATE cities SET mipaquete_code = '47170000' WHERE LOWER(name) = LOWER('Chivolo');
UPDATE cities SET mipaquete_code = '47189000' WHERE LOWER(name) = LOWER('Ciénaga');
UPDATE cities SET mipaquete_code = '47205000' WHERE LOWER(name) = LOWER('Concordia');
UPDATE cities SET mipaquete_code = '47245000' WHERE LOWER(name) = LOWER('El Banco');
UPDATE cities SET mipaquete_code = '47258000' WHERE LOWER(name) = LOWER('El Piñón');
UPDATE cities SET mipaquete_code = '47268000' WHERE LOWER(name) = LOWER('El Retén');
UPDATE cities SET mipaquete_code = '47288000' WHERE LOWER(name) = LOWER('Fundación');
UPDATE cities SET mipaquete_code = '47318000' WHERE LOWER(name) = LOWER('Guamal');
UPDATE cities SET mipaquete_code = '47460000' WHERE LOWER(name) = LOWER('Nueva Granada');
UPDATE cities SET mipaquete_code = '47541000' WHERE LOWER(name) = LOWER('Pedraza');
UPDATE cities SET mipaquete_code = '47545000' WHERE LOWER(name) = LOWER('Pijiño Del Carmen');
UPDATE cities SET mipaquete_code = '47551000' WHERE LOWER(name) = LOWER('Pivijay');
UPDATE cities SET mipaquete_code = '47555000' WHERE LOWER(name) = LOWER('Plato');
UPDATE cities SET mipaquete_code = '47570000' WHERE LOWER(name) = LOWER('Puebloviejo');
UPDATE cities SET mipaquete_code = '47605000' WHERE LOWER(name) = LOWER('Remolino');
UPDATE cities SET mipaquete_code = '47660000' WHERE LOWER(name) = LOWER('Sabanas De San Ángel');
UPDATE cities SET mipaquete_code = '47675000' WHERE LOWER(name) = LOWER('Salamina');
UPDATE cities SET mipaquete_code = '47692000' WHERE LOWER(name) = LOWER('San Sebastián De Buenavista');
UPDATE cities SET mipaquete_code = '47703000' WHERE LOWER(name) = LOWER('San Zenón');
UPDATE cities SET mipaquete_code = '47707000' WHERE LOWER(name) = LOWER('Santa Ana');
UPDATE cities SET mipaquete_code = '47720000' WHERE LOWER(name) = LOWER('Santa Bárbara De Pinto');
UPDATE cities SET mipaquete_code = '47745000' WHERE LOWER(name) = LOWER('Sitionuevo');
UPDATE cities SET mipaquete_code = '47798000' WHERE LOWER(name) = LOWER('Tenerife');
UPDATE cities SET mipaquete_code = '47960000' WHERE LOWER(name) = LOWER('Zapayán');
UPDATE cities SET mipaquete_code = '47980000' WHERE LOWER(name) = LOWER('Zona Bananera');
UPDATE cities SET mipaquete_code = '50001000' WHERE LOWER(name) = LOWER('Villavicencio');
UPDATE cities SET mipaquete_code = '50006000' WHERE LOWER(name) = LOWER('Acacías');
UPDATE cities SET mipaquete_code = '50110000' WHERE LOWER(name) = LOWER('Barranca De Upía');
UPDATE cities SET mipaquete_code = '50124000' WHERE LOWER(name) = LOWER('Cabuyaro');
UPDATE cities SET mipaquete_code = '50150000' WHERE LOWER(name) = LOWER('Castilla La Nueva');
UPDATE cities SET mipaquete_code = '50223000' WHERE LOWER(name) = LOWER('Cubarral');
UPDATE cities SET mipaquete_code = '50226000' WHERE LOWER(name) = LOWER('Cumaral');
UPDATE cities SET mipaquete_code = '50245000' WHERE LOWER(name) = LOWER('El Calvario');
UPDATE cities SET mipaquete_code = '50251000' WHERE LOWER(name) = LOWER('El Castillo');
UPDATE cities SET mipaquete_code = '50270000' WHERE LOWER(name) = LOWER('El Dorado');
UPDATE cities SET mipaquete_code = '50287000' WHERE LOWER(name) = LOWER('Fuente De Oro');
UPDATE cities SET mipaquete_code = '50313000' WHERE LOWER(name) = LOWER('Granada');
UPDATE cities SET mipaquete_code = '50318000' WHERE LOWER(name) = LOWER('Guamal');
UPDATE cities SET mipaquete_code = '50325000' WHERE LOWER(name) = LOWER('Mapiripán');
UPDATE cities SET mipaquete_code = '50330000' WHERE LOWER(name) = LOWER('Mesetas');
UPDATE cities SET mipaquete_code = '50350000' WHERE LOWER(name) = LOWER('La Macarena');
UPDATE cities SET mipaquete_code = '50370000' WHERE LOWER(name) = LOWER('Uribe');
UPDATE cities SET mipaquete_code = '50400000' WHERE LOWER(name) = LOWER('Lejanías');
UPDATE cities SET mipaquete_code = '50450000' WHERE LOWER(name) = LOWER('Puerto Concordia');
UPDATE cities SET mipaquete_code = '50568000' WHERE LOWER(name) = LOWER('Puerto Gaitán');
UPDATE cities SET mipaquete_code = '50573000' WHERE LOWER(name) = LOWER('Puerto López');
UPDATE cities SET mipaquete_code = '50577000' WHERE LOWER(name) = LOWER('Puerto Lleras');
UPDATE cities SET mipaquete_code = '50590000' WHERE LOWER(name) = LOWER('Puerto Rico');
UPDATE cities SET mipaquete_code = '50606000' WHERE LOWER(name) = LOWER('Restrepo');
UPDATE cities SET mipaquete_code = '50680000' WHERE LOWER(name) = LOWER('San Carlos De Guaroa');
UPDATE cities SET mipaquete_code = '50683000' WHERE LOWER(name) = LOWER('San Juan De Arama');
UPDATE cities SET mipaquete_code = '50686000' WHERE LOWER(name) = LOWER('San Juanito');
UPDATE cities SET mipaquete_code = '50689000' WHERE LOWER(name) = LOWER('San Martín');
UPDATE cities SET mipaquete_code = '50711000' WHERE LOWER(name) = LOWER('Vistahermosa');
UPDATE cities SET mipaquete_code = '52001000' WHERE LOWER(name) = LOWER('Pasto');
UPDATE cities SET mipaquete_code = '52019000' WHERE LOWER(name) = LOWER('Albán');
UPDATE cities SET mipaquete_code = '52022000' WHERE LOWER(name) = LOWER('Aldana');
UPDATE cities SET mipaquete_code = '52036000' WHERE LOWER(name) = LOWER('Ancuya');
UPDATE cities SET mipaquete_code = '52051000' WHERE LOWER(name) = LOWER('Arboleda');
UPDATE cities SET mipaquete_code = '52079000' WHERE LOWER(name) = LOWER('Barbacoas');
UPDATE cities SET mipaquete_code = '52083000' WHERE LOWER(name) = LOWER('Belén');
UPDATE cities SET mipaquete_code = '52110000' WHERE LOWER(name) = LOWER('Buesaco');
UPDATE cities SET mipaquete_code = '52203000' WHERE LOWER(name) = LOWER('Colón');
UPDATE cities SET mipaquete_code = '52207000' WHERE LOWER(name) = LOWER('Consacá');
UPDATE cities SET mipaquete_code = '52210000' WHERE LOWER(name) = LOWER('Contadero');
UPDATE cities SET mipaquete_code = '52215000' WHERE LOWER(name) = LOWER('Córdoba');
UPDATE cities SET mipaquete_code = '52224000' WHERE LOWER(name) = LOWER('Cuaspud Carlosama');
UPDATE cities SET mipaquete_code = '52227000' WHERE LOWER(name) = LOWER('Cumbal');
UPDATE cities SET mipaquete_code = '52233000' WHERE LOWER(name) = LOWER('Cumbitara');
UPDATE cities SET mipaquete_code = '52240000' WHERE LOWER(name) = LOWER('Chachagüí');
UPDATE cities SET mipaquete_code = '52250000' WHERE LOWER(name) = LOWER('El Charco');
UPDATE cities SET mipaquete_code = '52254000' WHERE LOWER(name) = LOWER('El Peñol');
UPDATE cities SET mipaquete_code = '52256000' WHERE LOWER(name) = LOWER('El Rosario');
UPDATE cities SET mipaquete_code = '52258000' WHERE LOWER(name) = LOWER('El Tablón De Gómez');
UPDATE cities SET mipaquete_code = '52260000' WHERE LOWER(name) = LOWER('El Tambo');
UPDATE cities SET mipaquete_code = '52287000' WHERE LOWER(name) = LOWER('Funes');
UPDATE cities SET mipaquete_code = '52317000' WHERE LOWER(name) = LOWER('Guachucal');
UPDATE cities SET mipaquete_code = '52320000' WHERE LOWER(name) = LOWER('Guaitarilla');
UPDATE cities SET mipaquete_code = '52323000' WHERE LOWER(name) = LOWER('Gualmatán');
UPDATE cities SET mipaquete_code = '52352000' WHERE LOWER(name) = LOWER('Iles');
UPDATE cities SET mipaquete_code = '52354000' WHERE LOWER(name) = LOWER('Imués');
UPDATE cities SET mipaquete_code = '52356000' WHERE LOWER(name) = LOWER('Ipiales');
UPDATE cities SET mipaquete_code = '52378000' WHERE LOWER(name) = LOWER('La Cruz');
UPDATE cities SET mipaquete_code = '52381000' WHERE LOWER(name) = LOWER('La Florida');
UPDATE cities SET mipaquete_code = '52385000' WHERE LOWER(name) = LOWER('La Llanada');
UPDATE cities SET mipaquete_code = '52390000' WHERE LOWER(name) = LOWER('La Tola');
UPDATE cities SET mipaquete_code = '52399000' WHERE LOWER(name) = LOWER('La Unión');
UPDATE cities SET mipaquete_code = '52405000' WHERE LOWER(name) = LOWER('Leiva');
UPDATE cities SET mipaquete_code = '52411000' WHERE LOWER(name) = LOWER('Linares');
UPDATE cities SET mipaquete_code = '52418000' WHERE LOWER(name) = LOWER('Los Andes');
UPDATE cities SET mipaquete_code = '52427000' WHERE LOWER(name) = LOWER('Magüí');
UPDATE cities SET mipaquete_code = '52435000' WHERE LOWER(name) = LOWER('Mallama');
UPDATE cities SET mipaquete_code = '52473000' WHERE LOWER(name) = LOWER('Mosquera');
UPDATE cities SET mipaquete_code = '52480000' WHERE LOWER(name) = LOWER('Nariño');
UPDATE cities SET mipaquete_code = '52490000' WHERE LOWER(name) = LOWER('Olaya Herrera');
UPDATE cities SET mipaquete_code = '52506000' WHERE LOWER(name) = LOWER('Ospina');
UPDATE cities SET mipaquete_code = '52520000' WHERE LOWER(name) = LOWER('Francisco Pizarro');
UPDATE cities SET mipaquete_code = '52540000' WHERE LOWER(name) = LOWER('Policarpa');
UPDATE cities SET mipaquete_code = '52560000' WHERE LOWER(name) = LOWER('Potosí');
UPDATE cities SET mipaquete_code = '52565000' WHERE LOWER(name) = LOWER('Providencia');
UPDATE cities SET mipaquete_code = '52573000' WHERE LOWER(name) = LOWER('Puerres');
UPDATE cities SET mipaquete_code = '52585000' WHERE LOWER(name) = LOWER('Pupiales');
UPDATE cities SET mipaquete_code = '52612000' WHERE LOWER(name) = LOWER('Ricaurte');
UPDATE cities SET mipaquete_code = '52621000' WHERE LOWER(name) = LOWER('Roberto Payán');
UPDATE cities SET mipaquete_code = '52678000' WHERE LOWER(name) = LOWER('Samaniego');
UPDATE cities SET mipaquete_code = '52683000' WHERE LOWER(name) = LOWER('Sandoná');
UPDATE cities SET mipaquete_code = '52685000' WHERE LOWER(name) = LOWER('San Bernardo');
UPDATE cities SET mipaquete_code = '52687000' WHERE LOWER(name) = LOWER('San Lorenzo');
UPDATE cities SET mipaquete_code = '52693000' WHERE LOWER(name) = LOWER('San Pablo');
UPDATE cities SET mipaquete_code = '52694000' WHERE LOWER(name) = LOWER('San Pedro De Cartago');
UPDATE cities SET mipaquete_code = '52696000' WHERE LOWER(name) = LOWER('Santa Bárbara');
UPDATE cities SET mipaquete_code = '52699000' WHERE LOWER(name) = LOWER('Santacruz');
UPDATE cities SET mipaquete_code = '52720000' WHERE LOWER(name) = LOWER('Sapuyes');
UPDATE cities SET mipaquete_code = '52786000' WHERE LOWER(name) = LOWER('Taminango');
UPDATE cities SET mipaquete_code = '52788000' WHERE LOWER(name) = LOWER('Tangua');
UPDATE cities SET mipaquete_code = '52835000' WHERE LOWER(name) = LOWER('San Andrés De Tumaco');
UPDATE cities SET mipaquete_code = '52838000' WHERE LOWER(name) = LOWER('Túquerres');
UPDATE cities SET mipaquete_code = '52885000' WHERE LOWER(name) = LOWER('Yacuanquer');
UPDATE cities SET mipaquete_code = '54001000' WHERE LOWER(name) = LOWER('San José De Cúcuta');
UPDATE cities SET mipaquete_code = '54003000' WHERE LOWER(name) = LOWER('Ábrego');
UPDATE cities SET mipaquete_code = '54051000' WHERE LOWER(name) = LOWER('Arboledas');
UPDATE cities SET mipaquete_code = '54099000' WHERE LOWER(name) = LOWER('Bochalema');
UPDATE cities SET mipaquete_code = '54109000' WHERE LOWER(name) = LOWER('Bucarasica');
UPDATE cities SET mipaquete_code = '54125000' WHERE LOWER(name) = LOWER('Cácota');
UPDATE cities SET mipaquete_code = '54128000' WHERE LOWER(name) = LOWER('Cáchira');
UPDATE cities SET mipaquete_code = '54172000' WHERE LOWER(name) = LOWER('Chinácota');
UPDATE cities SET mipaquete_code = '54174000' WHERE LOWER(name) = LOWER('Chitagá');
UPDATE cities SET mipaquete_code = '54206000' WHERE LOWER(name) = LOWER('Convención');
UPDATE cities SET mipaquete_code = '54223000' WHERE LOWER(name) = LOWER('Cucutilla');
UPDATE cities SET mipaquete_code = '54239000' WHERE LOWER(name) = LOWER('Durania');
UPDATE cities SET mipaquete_code = '54245000' WHERE LOWER(name) = LOWER('El Carmen');
UPDATE cities SET mipaquete_code = '54250000' WHERE LOWER(name) = LOWER('El Tarra');
UPDATE cities SET mipaquete_code = '54261000' WHERE LOWER(name) = LOWER('El Zulia');
UPDATE cities SET mipaquete_code = '54313000' WHERE LOWER(name) = LOWER('Gramalote');
UPDATE cities SET mipaquete_code = '54344000' WHERE LOWER(name) = LOWER('Hacarí');
UPDATE cities SET mipaquete_code = '54347000' WHERE LOWER(name) = LOWER('Herrán');
UPDATE cities SET mipaquete_code = '54377000' WHERE LOWER(name) = LOWER('Labateca');
UPDATE cities SET mipaquete_code = '54385000' WHERE LOWER(name) = LOWER('La Esperanza');
UPDATE cities SET mipaquete_code = '54398000' WHERE LOWER(name) = LOWER('La Playa');
UPDATE cities SET mipaquete_code = '54405000' WHERE LOWER(name) = LOWER('Los Patios');
UPDATE cities SET mipaquete_code = '54418000' WHERE LOWER(name) = LOWER('Lourdes');
UPDATE cities SET mipaquete_code = '54480000' WHERE LOWER(name) = LOWER('Mutiscua');
UPDATE cities SET mipaquete_code = '54498000' WHERE LOWER(name) = LOWER('Ocaña');
UPDATE cities SET mipaquete_code = '54518000' WHERE LOWER(name) = LOWER('Pamplona');
UPDATE cities SET mipaquete_code = '54520000' WHERE LOWER(name) = LOWER('Pamplonita');
UPDATE cities SET mipaquete_code = '54553000' WHERE LOWER(name) = LOWER('Puerto Santander');
UPDATE cities SET mipaquete_code = '54599000' WHERE LOWER(name) = LOWER('Ragonvalia');
UPDATE cities SET mipaquete_code = '54660000' WHERE LOWER(name) = LOWER('Salazar');
UPDATE cities SET mipaquete_code = '54670000' WHERE LOWER(name) = LOWER('San Calixto');
UPDATE cities SET mipaquete_code = '54673000' WHERE LOWER(name) = LOWER('San Cayetano');
UPDATE cities SET mipaquete_code = '54680000' WHERE LOWER(name) = LOWER('Santiago');
UPDATE cities SET mipaquete_code = '54720000' WHERE LOWER(name) = LOWER('Sardinata');
UPDATE cities SET mipaquete_code = '54743000' WHERE LOWER(name) = LOWER('Silos');
UPDATE cities SET mipaquete_code = '54800000' WHERE LOWER(name) = LOWER('Teorama');
UPDATE cities SET mipaquete_code = '54810000' WHERE LOWER(name) = LOWER('Tibú');
UPDATE cities SET mipaquete_code = '54820000' WHERE LOWER(name) = LOWER('Toledo');
UPDATE cities SET mipaquete_code = '54871000' WHERE LOWER(name) = LOWER('Villa Caro');
UPDATE cities SET mipaquete_code = '54874000' WHERE LOWER(name) = LOWER('Villa Del Rosario');
UPDATE cities SET mipaquete_code = '63001000' WHERE LOWER(name) = LOWER('Armenia');
UPDATE cities SET mipaquete_code = '63111000' WHERE LOWER(name) = LOWER('Buenavista');
UPDATE cities SET mipaquete_code = '63130000' WHERE LOWER(name) = LOWER('Calarcá');
UPDATE cities SET mipaquete_code = '63190000' WHERE LOWER(name) = LOWER('Circasia');
UPDATE cities SET mipaquete_code = '63212000' WHERE LOWER(name) = LOWER('Córdoba');
UPDATE cities SET mipaquete_code = '63272000' WHERE LOWER(name) = LOWER('Filandia');
UPDATE cities SET mipaquete_code = '63302000' WHERE LOWER(name) = LOWER('Génova');
UPDATE cities SET mipaquete_code = '63401000' WHERE LOWER(name) = LOWER('La Tebaida');
UPDATE cities SET mipaquete_code = '63470000' WHERE LOWER(name) = LOWER('Montenegro');
UPDATE cities SET mipaquete_code = '63548000' WHERE LOWER(name) = LOWER('Pijao');
UPDATE cities SET mipaquete_code = '63594000' WHERE LOWER(name) = LOWER('Quimbaya');
UPDATE cities SET mipaquete_code = '63690000' WHERE LOWER(name) = LOWER('Salento');
UPDATE cities SET mipaquete_code = '66001000' WHERE LOWER(name) = LOWER('Pereira');
UPDATE cities SET mipaquete_code = '66045000' WHERE LOWER(name) = LOWER('Apía');
UPDATE cities SET mipaquete_code = '66075000' WHERE LOWER(name) = LOWER('Balboa');
UPDATE cities SET mipaquete_code = '66088000' WHERE LOWER(name) = LOWER('Belén De Umbría');
UPDATE cities SET mipaquete_code = '66170000' WHERE LOWER(name) = LOWER('Dosquebradas');
UPDATE cities SET mipaquete_code = '66318000' WHERE LOWER(name) = LOWER('Guática');
UPDATE cities SET mipaquete_code = '66383000' WHERE LOWER(name) = LOWER('La Celia');
UPDATE cities SET mipaquete_code = '66400000' WHERE LOWER(name) = LOWER('La Virginia');
UPDATE cities SET mipaquete_code = '66440000' WHERE LOWER(name) = LOWER('Marsella');
UPDATE cities SET mipaquete_code = '66456000' WHERE LOWER(name) = LOWER('Mistrató');
UPDATE cities SET mipaquete_code = '66572000' WHERE LOWER(name) = LOWER('Pueblo Rico');
UPDATE cities SET mipaquete_code = '66594000' WHERE LOWER(name) = LOWER('Quinchía');
UPDATE cities SET mipaquete_code = '66682000' WHERE LOWER(name) = LOWER('Santa Rosa De Cabal');
UPDATE cities SET mipaquete_code = '66687000' WHERE LOWER(name) = LOWER('Santuario');
UPDATE cities SET mipaquete_code = '68001000' WHERE LOWER(name) = LOWER('Bucaramanga');
UPDATE cities SET mipaquete_code = '68013000' WHERE LOWER(name) = LOWER('Aguada');
UPDATE cities SET mipaquete_code = '68020000' WHERE LOWER(name) = LOWER('Albania');
UPDATE cities SET mipaquete_code = '68051000' WHERE LOWER(name) = LOWER('Aratoca');
UPDATE cities SET mipaquete_code = '68077000' WHERE LOWER(name) = LOWER('Barbosa');
UPDATE cities SET mipaquete_code = '68079000' WHERE LOWER(name) = LOWER('Barichara');
UPDATE cities SET mipaquete_code = '68081000' WHERE LOWER(name) = LOWER('Barrancabermeja');
UPDATE cities SET mipaquete_code = '68092000' WHERE LOWER(name) = LOWER('Betulia');
UPDATE cities SET mipaquete_code = '68101000' WHERE LOWER(name) = LOWER('Bolívar');
UPDATE cities SET mipaquete_code = '68121000' WHERE LOWER(name) = LOWER('Cabrera');
UPDATE cities SET mipaquete_code = '68132000' WHERE LOWER(name) = LOWER('California');
UPDATE cities SET mipaquete_code = '68147000' WHERE LOWER(name) = LOWER('Capitanejo');
UPDATE cities SET mipaquete_code = '68152000' WHERE LOWER(name) = LOWER('Carcasí');
UPDATE cities SET mipaquete_code = '68160000' WHERE LOWER(name) = LOWER('Cepitá');
UPDATE cities SET mipaquete_code = '68162000' WHERE LOWER(name) = LOWER('Cerrito');
UPDATE cities SET mipaquete_code = '68167000' WHERE LOWER(name) = LOWER('Charalá');
UPDATE cities SET mipaquete_code = '68169000' WHERE LOWER(name) = LOWER('Charta');
UPDATE cities SET mipaquete_code = '68176000' WHERE LOWER(name) = LOWER('Chima');
UPDATE cities SET mipaquete_code = '68179000' WHERE LOWER(name) = LOWER('Chipatá');
UPDATE cities SET mipaquete_code = '68190000' WHERE LOWER(name) = LOWER('Cimitarra');
UPDATE cities SET mipaquete_code = '68207000' WHERE LOWER(name) = LOWER('Concepción');
UPDATE cities SET mipaquete_code = '68209000' WHERE LOWER(name) = LOWER('Confines');
UPDATE cities SET mipaquete_code = '68211000' WHERE LOWER(name) = LOWER('Contratación');
UPDATE cities SET mipaquete_code = '68217000' WHERE LOWER(name) = LOWER('Coromoro');
UPDATE cities SET mipaquete_code = '68229000' WHERE LOWER(name) = LOWER('Curití');
UPDATE cities SET mipaquete_code = '68235000' WHERE LOWER(name) = LOWER('El Carmen De Chucurí');
UPDATE cities SET mipaquete_code = '68245000' WHERE LOWER(name) = LOWER('El Guacamayo');
UPDATE cities SET mipaquete_code = '68250000' WHERE LOWER(name) = LOWER('El Peñón');
UPDATE cities SET mipaquete_code = '68255000' WHERE LOWER(name) = LOWER('El Playón');
UPDATE cities SET mipaquete_code = '68264000' WHERE LOWER(name) = LOWER('Encino');
UPDATE cities SET mipaquete_code = '68266000' WHERE LOWER(name) = LOWER('Enciso');
UPDATE cities SET mipaquete_code = '68271000' WHERE LOWER(name) = LOWER('Florián');
UPDATE cities SET mipaquete_code = '68276000' WHERE LOWER(name) = LOWER('Floridablanca');
UPDATE cities SET mipaquete_code = '68296000' WHERE LOWER(name) = LOWER('Galán');
UPDATE cities SET mipaquete_code = '68298000' WHERE LOWER(name) = LOWER('Gámbita');
UPDATE cities SET mipaquete_code = '68307000' WHERE LOWER(name) = LOWER('Girón');
UPDATE cities SET mipaquete_code = '68318000' WHERE LOWER(name) = LOWER('Guaca');
UPDATE cities SET mipaquete_code = '68320000' WHERE LOWER(name) = LOWER('Guadalupe');
UPDATE cities SET mipaquete_code = '68322000' WHERE LOWER(name) = LOWER('Guapotá');
UPDATE cities SET mipaquete_code = '68324000' WHERE LOWER(name) = LOWER('Guavatá');
UPDATE cities SET mipaquete_code = '68327000' WHERE LOWER(name) = LOWER('Güepsa');
UPDATE cities SET mipaquete_code = '68344000' WHERE LOWER(name) = LOWER('Hato');
UPDATE cities SET mipaquete_code = '68368000' WHERE LOWER(name) = LOWER('Jesús María');
UPDATE cities SET mipaquete_code = '68370000' WHERE LOWER(name) = LOWER('Jordán');
UPDATE cities SET mipaquete_code = '68377000' WHERE LOWER(name) = LOWER('La Belleza');
UPDATE cities SET mipaquete_code = '68385000' WHERE LOWER(name) = LOWER('Landázuri');
UPDATE cities SET mipaquete_code = '68397000' WHERE LOWER(name) = LOWER('La Paz');
UPDATE cities SET mipaquete_code = '68406000' WHERE LOWER(name) = LOWER('Lebrija');
UPDATE cities SET mipaquete_code = '68418000' WHERE LOWER(name) = LOWER('Los Santos');
UPDATE cities SET mipaquete_code = '68425000' WHERE LOWER(name) = LOWER('Macaravita');
UPDATE cities SET mipaquete_code = '68432000' WHERE LOWER(name) = LOWER('Málaga');
UPDATE cities SET mipaquete_code = '68444000' WHERE LOWER(name) = LOWER('Matanza');
UPDATE cities SET mipaquete_code = '68464000' WHERE LOWER(name) = LOWER('Mogotes');
UPDATE cities SET mipaquete_code = '68468000' WHERE LOWER(name) = LOWER('Molagavita');
UPDATE cities SET mipaquete_code = '68498000' WHERE LOWER(name) = LOWER('Ocamonte');
UPDATE cities SET mipaquete_code = '68500000' WHERE LOWER(name) = LOWER('Oiba');
UPDATE cities SET mipaquete_code = '68502000' WHERE LOWER(name) = LOWER('Onzaga');
UPDATE cities SET mipaquete_code = '68522000' WHERE LOWER(name) = LOWER('Palmar');
UPDATE cities SET mipaquete_code = '68524000' WHERE LOWER(name) = LOWER('Palmas Del Socorro');
UPDATE cities SET mipaquete_code = '68533000' WHERE LOWER(name) = LOWER('Páramo');
UPDATE cities SET mipaquete_code = '68547000' WHERE LOWER(name) = LOWER('Piedecuesta');
UPDATE cities SET mipaquete_code = '68549000' WHERE LOWER(name) = LOWER('Pinchote');
UPDATE cities SET mipaquete_code = '68572000' WHERE LOWER(name) = LOWER('Puente Nacional');
UPDATE cities SET mipaquete_code = '68573000' WHERE LOWER(name) = LOWER('Puerto Parra');
UPDATE cities SET mipaquete_code = '68575000' WHERE LOWER(name) = LOWER('Puerto Wilches');
UPDATE cities SET mipaquete_code = '68615000' WHERE LOWER(name) = LOWER('Rionegro');
UPDATE cities SET mipaquete_code = '68655000' WHERE LOWER(name) = LOWER('Sabana De Torres');
UPDATE cities SET mipaquete_code = '68669000' WHERE LOWER(name) = LOWER('San Andrés');
UPDATE cities SET mipaquete_code = '68673000' WHERE LOWER(name) = LOWER('San Benito');
UPDATE cities SET mipaquete_code = '68679000' WHERE LOWER(name) = LOWER('San Gil');
UPDATE cities SET mipaquete_code = '68682000' WHERE LOWER(name) = LOWER('San Joaquín');
UPDATE cities SET mipaquete_code = '68684000' WHERE LOWER(name) = LOWER('San José De Miranda');
UPDATE cities SET mipaquete_code = '68686000' WHERE LOWER(name) = LOWER('San Miguel');
UPDATE cities SET mipaquete_code = '68689000' WHERE LOWER(name) = LOWER('San Vicente De Chucurí');
UPDATE cities SET mipaquete_code = '68705000' WHERE LOWER(name) = LOWER('Santa Bárbara');
UPDATE cities SET mipaquete_code = '68720000' WHERE LOWER(name) = LOWER('Santa Helena Del Opón');
UPDATE cities SET mipaquete_code = '68745000' WHERE LOWER(name) = LOWER('Simacota');
UPDATE cities SET mipaquete_code = '68755000' WHERE LOWER(name) = LOWER('Socorro');
UPDATE cities SET mipaquete_code = '68770000' WHERE LOWER(name) = LOWER('Suaita');
UPDATE cities SET mipaquete_code = '68773000' WHERE LOWER(name) = LOWER('Sucre');
UPDATE cities SET mipaquete_code = '68780000' WHERE LOWER(name) = LOWER('Suratá');
UPDATE cities SET mipaquete_code = '68820000' WHERE LOWER(name) = LOWER('Tona');
UPDATE cities SET mipaquete_code = '68855000' WHERE LOWER(name) = LOWER('Valle De San José');
UPDATE cities SET mipaquete_code = '68861000' WHERE LOWER(name) = LOWER('Vélez');
UPDATE cities SET mipaquete_code = '68867000' WHERE LOWER(name) = LOWER('Vetas');
UPDATE cities SET mipaquete_code = '68872000' WHERE LOWER(name) = LOWER('Villanueva');
UPDATE cities SET mipaquete_code = '68895000' WHERE LOWER(name) = LOWER('Zapatoca');
UPDATE cities SET mipaquete_code = '70001000' WHERE LOWER(name) = LOWER('Sincelejo');
UPDATE cities SET mipaquete_code = '70110000' WHERE LOWER(name) = LOWER('Buenavista');
UPDATE cities SET mipaquete_code = '70124000' WHERE LOWER(name) = LOWER('Caimito');
UPDATE cities SET mipaquete_code = '70204000' WHERE LOWER(name) = LOWER('Colosó');
UPDATE cities SET mipaquete_code = '70215000' WHERE LOWER(name) = LOWER('Corozal');
UPDATE cities SET mipaquete_code = '70221000' WHERE LOWER(name) = LOWER('Coveñas');
UPDATE cities SET mipaquete_code = '70230000' WHERE LOWER(name) = LOWER('Chalán');
UPDATE cities SET mipaquete_code = '70233000' WHERE LOWER(name) = LOWER('El Roble');
UPDATE cities SET mipaquete_code = '70235000' WHERE LOWER(name) = LOWER('Galeras');
UPDATE cities SET mipaquete_code = '70265000' WHERE LOWER(name) = LOWER('Guaranda');
UPDATE cities SET mipaquete_code = '70400000' WHERE LOWER(name) = LOWER('La Unión');
UPDATE cities SET mipaquete_code = '70418000' WHERE LOWER(name) = LOWER('Los Palmitos');
UPDATE cities SET mipaquete_code = '70429000' WHERE LOWER(name) = LOWER('Majagual');
UPDATE cities SET mipaquete_code = '70473000' WHERE LOWER(name) = LOWER('Morroa');
UPDATE cities SET mipaquete_code = '70508000' WHERE LOWER(name) = LOWER('Ovejas');
UPDATE cities SET mipaquete_code = '70523000' WHERE LOWER(name) = LOWER('Palmito');
UPDATE cities SET mipaquete_code = '70670000' WHERE LOWER(name) = LOWER('Sampués');
UPDATE cities SET mipaquete_code = '70678000' WHERE LOWER(name) = LOWER('San Benito Abad');
UPDATE cities SET mipaquete_code = '70702000' WHERE LOWER(name) = LOWER('San Juan De Betulia');
UPDATE cities SET mipaquete_code = '70708000' WHERE LOWER(name) = LOWER('San Marcos');
UPDATE cities SET mipaquete_code = '70713000' WHERE LOWER(name) = LOWER('San Onofre');
UPDATE cities SET mipaquete_code = '70717000' WHERE LOWER(name) = LOWER('San Pedro');
UPDATE cities SET mipaquete_code = '70742000' WHERE LOWER(name) = LOWER('San Luis De Sincé');
UPDATE cities SET mipaquete_code = '70771000' WHERE LOWER(name) = LOWER('Sucre');
UPDATE cities SET mipaquete_code = '70820000' WHERE LOWER(name) = LOWER('Santiago De Tolú');
UPDATE cities SET mipaquete_code = '70823000' WHERE LOWER(name) = LOWER('San José De Toluviejo');
UPDATE cities SET mipaquete_code = '73001000' WHERE LOWER(name) = LOWER('Ibagué');
UPDATE cities SET mipaquete_code = '73024000' WHERE LOWER(name) = LOWER('Alpujarra');
UPDATE cities SET mipaquete_code = '73026000' WHERE LOWER(name) = LOWER('Alvarado');
UPDATE cities SET mipaquete_code = '73030000' WHERE LOWER(name) = LOWER('Ambalema');
UPDATE cities SET mipaquete_code = '73043000' WHERE LOWER(name) = LOWER('Anzoátegui');
UPDATE cities SET mipaquete_code = '73055000' WHERE LOWER(name) = LOWER('Armero');
UPDATE cities SET mipaquete_code = '73067000' WHERE LOWER(name) = LOWER('Ataco');
UPDATE cities SET mipaquete_code = '73124000' WHERE LOWER(name) = LOWER('Cajamarca');
UPDATE cities SET mipaquete_code = '73148000' WHERE LOWER(name) = LOWER('Carmen De Apicalá');
UPDATE cities SET mipaquete_code = '73152000' WHERE LOWER(name) = LOWER('Casabianca');
UPDATE cities SET mipaquete_code = '73168000' WHERE LOWER(name) = LOWER('Chaparral');
UPDATE cities SET mipaquete_code = '73200000' WHERE LOWER(name) = LOWER('Coello');
UPDATE cities SET mipaquete_code = '73217000' WHERE LOWER(name) = LOWER('Coyaima');
UPDATE cities SET mipaquete_code = '73226000' WHERE LOWER(name) = LOWER('Cunday');
UPDATE cities SET mipaquete_code = '73236000' WHERE LOWER(name) = LOWER('Dolores');
UPDATE cities SET mipaquete_code = '73268000' WHERE LOWER(name) = LOWER('Espinal');
UPDATE cities SET mipaquete_code = '73270000' WHERE LOWER(name) = LOWER('Falan');
UPDATE cities SET mipaquete_code = '73275000' WHERE LOWER(name) = LOWER('Flandes');
UPDATE cities SET mipaquete_code = '73283000' WHERE LOWER(name) = LOWER('Fresno');
UPDATE cities SET mipaquete_code = '73319000' WHERE LOWER(name) = LOWER('Guamo');
UPDATE cities SET mipaquete_code = '73347000' WHERE LOWER(name) = LOWER('Herveo');
UPDATE cities SET mipaquete_code = '73349000' WHERE LOWER(name) = LOWER('Honda');
UPDATE cities SET mipaquete_code = '73352000' WHERE LOWER(name) = LOWER('Icononzo');
UPDATE cities SET mipaquete_code = '73408000' WHERE LOWER(name) = LOWER('Lérida');
UPDATE cities SET mipaquete_code = '73411000' WHERE LOWER(name) = LOWER('Líbano');
UPDATE cities SET mipaquete_code = '73443000' WHERE LOWER(name) = LOWER('San Sebastián De Mariquita');
UPDATE cities SET mipaquete_code = '73449000' WHERE LOWER(name) = LOWER('Melgar');
UPDATE cities SET mipaquete_code = '73461000' WHERE LOWER(name) = LOWER('Murillo');
UPDATE cities SET mipaquete_code = '73483000' WHERE LOWER(name) = LOWER('Natagaima');
UPDATE cities SET mipaquete_code = '73504000' WHERE LOWER(name) = LOWER('Ortega');
UPDATE cities SET mipaquete_code = '73520000' WHERE LOWER(name) = LOWER('Palocabildo');
UPDATE cities SET mipaquete_code = '73547000' WHERE LOWER(name) = LOWER('Piedras');
UPDATE cities SET mipaquete_code = '73555000' WHERE LOWER(name) = LOWER('Planadas');
UPDATE cities SET mipaquete_code = '73563000' WHERE LOWER(name) = LOWER('Prado');
UPDATE cities SET mipaquete_code = '73585000' WHERE LOWER(name) = LOWER('Purificación');
UPDATE cities SET mipaquete_code = '73616000' WHERE LOWER(name) = LOWER('Rioblanco');
UPDATE cities SET mipaquete_code = '73622000' WHERE LOWER(name) = LOWER('Roncesvalles');
UPDATE cities SET mipaquete_code = '73624000' WHERE LOWER(name) = LOWER('Rovira');
UPDATE cities SET mipaquete_code = '73671000' WHERE LOWER(name) = LOWER('Saldaña');
UPDATE cities SET mipaquete_code = '73675000' WHERE LOWER(name) = LOWER('San Antonio');
UPDATE cities SET mipaquete_code = '73678000' WHERE LOWER(name) = LOWER('San Luis');
UPDATE cities SET mipaquete_code = '73686000' WHERE LOWER(name) = LOWER('Santa Isabel');
UPDATE cities SET mipaquete_code = '73770000' WHERE LOWER(name) = LOWER('Suárez');
UPDATE cities SET mipaquete_code = '73854000' WHERE LOWER(name) = LOWER('Valle De San Juan');
UPDATE cities SET mipaquete_code = '73861000' WHERE LOWER(name) = LOWER('Venadillo');
UPDATE cities SET mipaquete_code = '73870000' WHERE LOWER(name) = LOWER('Villahermosa');
UPDATE cities SET mipaquete_code = '73873000' WHERE LOWER(name) = LOWER('Villarrica');
UPDATE cities SET mipaquete_code = '76001000' WHERE LOWER(name) = LOWER('Santiago De Cali');
UPDATE cities SET mipaquete_code = '76020000' WHERE LOWER(name) = LOWER('Alcalá');
UPDATE cities SET mipaquete_code = '76036000' WHERE LOWER(name) = LOWER('Andalucía');
UPDATE cities SET mipaquete_code = '76041000' WHERE LOWER(name) = LOWER('Ansermanuevo');
UPDATE cities SET mipaquete_code = '76054000' WHERE LOWER(name) = LOWER('Argelia');
UPDATE cities SET mipaquete_code = '76100000' WHERE LOWER(name) = LOWER('Bolívar');
UPDATE cities SET mipaquete_code = '76109000' WHERE LOWER(name) = LOWER('Buenaventura');
UPDATE cities SET mipaquete_code = '76111000' WHERE LOWER(name) = LOWER('Guadalajara De Buga');
UPDATE cities SET mipaquete_code = '76113000' WHERE LOWER(name) = LOWER('Bugalagrande');
UPDATE cities SET mipaquete_code = '76122000' WHERE LOWER(name) = LOWER('Caicedonia');
UPDATE cities SET mipaquete_code = '76126000' WHERE LOWER(name) = LOWER('Calima');
UPDATE cities SET mipaquete_code = '76130000' WHERE LOWER(name) = LOWER('Candelaria');
UPDATE cities SET mipaquete_code = '76147000' WHERE LOWER(name) = LOWER('Cartago');
UPDATE cities SET mipaquete_code = '76233000' WHERE LOWER(name) = LOWER('Dagua');
UPDATE cities SET mipaquete_code = '76243000' WHERE LOWER(name) = LOWER('El Águila');
UPDATE cities SET mipaquete_code = '76246000' WHERE LOWER(name) = LOWER('El Cairo');
UPDATE cities SET mipaquete_code = '76248000' WHERE LOWER(name) = LOWER('El Cerrito');
UPDATE cities SET mipaquete_code = '76250000' WHERE LOWER(name) = LOWER('El Dovio');
UPDATE cities SET mipaquete_code = '76275000' WHERE LOWER(name) = LOWER('Florida');
UPDATE cities SET mipaquete_code = '76306000' WHERE LOWER(name) = LOWER('Ginebra');
UPDATE cities SET mipaquete_code = '76318000' WHERE LOWER(name) = LOWER('Guacarí');
UPDATE cities SET mipaquete_code = '76364000' WHERE LOWER(name) = LOWER('Jamundí');
UPDATE cities SET mipaquete_code = '76377000' WHERE LOWER(name) = LOWER('La Cumbre');
UPDATE cities SET mipaquete_code = '76400000' WHERE LOWER(name) = LOWER('La Unión');
UPDATE cities SET mipaquete_code = '76403000' WHERE LOWER(name) = LOWER('La Victoria');
UPDATE cities SET mipaquete_code = '76497000' WHERE LOWER(name) = LOWER('Obando');
UPDATE cities SET mipaquete_code = '76520000' WHERE LOWER(name) = LOWER('Palmira');
UPDATE cities SET mipaquete_code = '76563000' WHERE LOWER(name) = LOWER('Pradera');
UPDATE cities SET mipaquete_code = '76606000' WHERE LOWER(name) = LOWER('Restrepo');
UPDATE cities SET mipaquete_code = '76616000' WHERE LOWER(name) = LOWER('Riofrío');
UPDATE cities SET mipaquete_code = '76622000' WHERE LOWER(name) = LOWER('Roldanillo');
UPDATE cities SET mipaquete_code = '76670000' WHERE LOWER(name) = LOWER('San Pedro');
UPDATE cities SET mipaquete_code = '76736000' WHERE LOWER(name) = LOWER('Sevilla');
UPDATE cities SET mipaquete_code = '76823000' WHERE LOWER(name) = LOWER('Toro');
UPDATE cities SET mipaquete_code = '76828000' WHERE LOWER(name) = LOWER('Trujillo');
UPDATE cities SET mipaquete_code = '76834000' WHERE LOWER(name) = LOWER('Tuluá');
UPDATE cities SET mipaquete_code = '76845000' WHERE LOWER(name) = LOWER('Ulloa');
UPDATE cities SET mipaquete_code = '76863000' WHERE LOWER(name) = LOWER('Versalles');
UPDATE cities SET mipaquete_code = '76869000' WHERE LOWER(name) = LOWER('Vijes');
UPDATE cities SET mipaquete_code = '76890000' WHERE LOWER(name) = LOWER('Yotoco');
UPDATE cities SET mipaquete_code = '76892000' WHERE LOWER(name) = LOWER('Yumbo');
UPDATE cities SET mipaquete_code = '76895000' WHERE LOWER(name) = LOWER('Zarzal');
UPDATE cities SET mipaquete_code = '81001000' WHERE LOWER(name) = LOWER('Arauca');
UPDATE cities SET mipaquete_code = '81065000' WHERE LOWER(name) = LOWER('Arauquita');
UPDATE cities SET mipaquete_code = '81220000' WHERE LOWER(name) = LOWER('Cravo Norte');
UPDATE cities SET mipaquete_code = '81300000' WHERE LOWER(name) = LOWER('Fortul');
UPDATE cities SET mipaquete_code = '81591000' WHERE LOWER(name) = LOWER('Puerto Rondón');
UPDATE cities SET mipaquete_code = '81736000' WHERE LOWER(name) = LOWER('Saravena');
UPDATE cities SET mipaquete_code = '81794000' WHERE LOWER(name) = LOWER('Tame');
UPDATE cities SET mipaquete_code = '85001000' WHERE LOWER(name) = LOWER('Yopal');
UPDATE cities SET mipaquete_code = '85010000' WHERE LOWER(name) = LOWER('Aguazul');
UPDATE cities SET mipaquete_code = '85015000' WHERE LOWER(name) = LOWER('Chámeza');
UPDATE cities SET mipaquete_code = '85125000' WHERE LOWER(name) = LOWER('Hato Corozal');
UPDATE cities SET mipaquete_code = '85136000' WHERE LOWER(name) = LOWER('La Salina');
UPDATE cities SET mipaquete_code = '85139000' WHERE LOWER(name) = LOWER('Maní');
UPDATE cities SET mipaquete_code = '85162000' WHERE LOWER(name) = LOWER('Monterrey');
UPDATE cities SET mipaquete_code = '85225000' WHERE LOWER(name) = LOWER('Nunchía');
UPDATE cities SET mipaquete_code = '85230000' WHERE LOWER(name) = LOWER('Orocué');
UPDATE cities SET mipaquete_code = '85250000' WHERE LOWER(name) = LOWER('Paz De Ariporo');
UPDATE cities SET mipaquete_code = '85263000' WHERE LOWER(name) = LOWER('Pore');
UPDATE cities SET mipaquete_code = '85279000' WHERE LOWER(name) = LOWER('Recetor');
UPDATE cities SET mipaquete_code = '85300000' WHERE LOWER(name) = LOWER('Sabanalarga');
UPDATE cities SET mipaquete_code = '85315000' WHERE LOWER(name) = LOWER('Sácama');
UPDATE cities SET mipaquete_code = '85325000' WHERE LOWER(name) = LOWER('San Luis De Palenque');
UPDATE cities SET mipaquete_code = '85400000' WHERE LOWER(name) = LOWER('Támara');
UPDATE cities SET mipaquete_code = '85410000' WHERE LOWER(name) = LOWER('Tauramena');
UPDATE cities SET mipaquete_code = '85430000' WHERE LOWER(name) = LOWER('Trinidad');
UPDATE cities SET mipaquete_code = '85440000' WHERE LOWER(name) = LOWER('Villanueva');
UPDATE cities SET mipaquete_code = '86001000' WHERE LOWER(name) = LOWER('Mocoa');
UPDATE cities SET mipaquete_code = '86219000' WHERE LOWER(name) = LOWER('Colón');
UPDATE cities SET mipaquete_code = '86320000' WHERE LOWER(name) = LOWER('Orito');
UPDATE cities SET mipaquete_code = '86568000' WHERE LOWER(name) = LOWER('Puerto Asís');
UPDATE cities SET mipaquete_code = '86569000' WHERE LOWER(name) = LOWER('Puerto Caicedo');
UPDATE cities SET mipaquete_code = '86571000' WHERE LOWER(name) = LOWER('Puerto Guzmán');
UPDATE cities SET mipaquete_code = '86573000' WHERE LOWER(name) = LOWER('Puerto Leguízamo');
UPDATE cities SET mipaquete_code = '86749000' WHERE LOWER(name) = LOWER('Sibundoy');
UPDATE cities SET mipaquete_code = '86755000' WHERE LOWER(name) = LOWER('San Francisco');
UPDATE cities SET mipaquete_code = '86757000' WHERE LOWER(name) = LOWER('San Miguel');
UPDATE cities SET mipaquete_code = '86760000' WHERE LOWER(name) = LOWER('Santiago');
UPDATE cities SET mipaquete_code = '86865000' WHERE LOWER(name) = LOWER('Valle Del Guamuez');
UPDATE cities SET mipaquete_code = '86885000' WHERE LOWER(name) = LOWER('Villagarzón');
UPDATE cities SET mipaquete_code = '88001000' WHERE LOWER(name) = LOWER('San Andrés');
UPDATE cities SET mipaquete_code = '88564000' WHERE LOWER(name) = LOWER('Providencia');
UPDATE cities SET mipaquete_code = '91001000' WHERE LOWER(name) = LOWER('Leticia');
UPDATE cities SET mipaquete_code = '91263000' WHERE LOWER(name) = LOWER('El Encanto');
UPDATE cities SET mipaquete_code = '91405000' WHERE LOWER(name) = LOWER('La Chorrera');
UPDATE cities SET mipaquete_code = '91407000' WHERE LOWER(name) = LOWER('La Pedrera');
UPDATE cities SET mipaquete_code = '91430000' WHERE LOWER(name) = LOWER('La Victoria');
UPDATE cities SET mipaquete_code = '91460000' WHERE LOWER(name) = LOWER('Mirití - Paraná');
UPDATE cities SET mipaquete_code = '91530000' WHERE LOWER(name) = LOWER('Puerto Alegría');
UPDATE cities SET mipaquete_code = '91536000' WHERE LOWER(name) = LOWER('Puerto Arica');
UPDATE cities SET mipaquete_code = '91540000' WHERE LOWER(name) = LOWER('Puerto Nariño');
UPDATE cities SET mipaquete_code = '91669000' WHERE LOWER(name) = LOWER('Puerto Santander');
UPDATE cities SET mipaquete_code = '91798000' WHERE LOWER(name) = LOWER('Tarapacá');
UPDATE cities SET mipaquete_code = '94001000' WHERE LOWER(name) = LOWER('Inírida');
UPDATE cities SET mipaquete_code = '94343000' WHERE LOWER(name) = LOWER('Barrancominas');
UPDATE cities SET mipaquete_code = '94883000' WHERE LOWER(name) = LOWER('San Felipe');
UPDATE cities SET mipaquete_code = '94884000' WHERE LOWER(name) = LOWER('Puerto Colombia');
UPDATE cities SET mipaquete_code = '94885000' WHERE LOWER(name) = LOWER('La Guadalupe');
UPDATE cities SET mipaquete_code = '94886000' WHERE LOWER(name) = LOWER('Cacahual');
UPDATE cities SET mipaquete_code = '94887000' WHERE LOWER(name) = LOWER('Pana Pana');
UPDATE cities SET mipaquete_code = '94888000' WHERE LOWER(name) = LOWER('Morichal');
UPDATE cities SET mipaquete_code = '95001000' WHERE LOWER(name) = LOWER('San José Del Guaviare');
UPDATE cities SET mipaquete_code = '95015000' WHERE LOWER(name) = LOWER('Calamar');
UPDATE cities SET mipaquete_code = '95025000' WHERE LOWER(name) = LOWER('El Retorno');
UPDATE cities SET mipaquete_code = '95200000' WHERE LOWER(name) = LOWER('Miraflores');
UPDATE cities SET mipaquete_code = '97001000' WHERE LOWER(name) = LOWER('Mitú');
UPDATE cities SET mipaquete_code = '97161000' WHERE LOWER(name) = LOWER('Carurú');
UPDATE cities SET mipaquete_code = '97511000' WHERE LOWER(name) = LOWER('Pacoa');
UPDATE cities SET mipaquete_code = '97666000' WHERE LOWER(name) = LOWER('Taraira');
UPDATE cities SET mipaquete_code = '97777000' WHERE LOWER(name) = LOWER('Papunahua');
UPDATE cities SET mipaquete_code = '97889000' WHERE LOWER(name) = LOWER('Yavaraté');
UPDATE cities SET mipaquete_code = '99001000' WHERE LOWER(name) = LOWER('Puerto Carreño');
UPDATE cities SET mipaquete_code = '99524000' WHERE LOWER(name) = LOWER('La Primavera');
UPDATE cities SET mipaquete_code = '99624000' WHERE LOWER(name) = LOWER('Santa Rosalía');
UPDATE cities SET mipaquete_code = '99773000' WHERE LOWER(name) = LOWER('Cumaribo');

-- Total: 1122 cities updated
-- Cities without a match keep mipaquete_code = NULL and use fixed delivery_cost
